import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `supabase start` (Edge Runtime bootstrap bundle) —
    // gitignored (supabase/.gitignore), regenerated fresh every start, and
    // minified, so linting it is both pointless and slow. Without this,
    // `npm run lint` picks up hundreds of false-positive errors from it
    // any time the local Supabase stack happens to be running.
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
