-- Generated by scripts/generate-seed-sql.ts from scripts/seed-data.ts.
-- Applied automatically by `supabase db reset` for local development.
-- Do not hand-edit — edit scripts/seed-data.ts and regenerate instead.

-- Seed author: a system account every seed prompt is attributed to.
-- Inserted directly into auth.users (standard local-seed pattern) so
-- the handle_new_user() trigger creates the matching profiles row.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at
)
values (
  '00000000-0000-0000-0000-000000000000',
  '00000000-0000-0000-0000-000000000001',
  'authenticated', 'authenticated', 'seed@devatlas.internal',
  crypt('5f99e0f3-c163-4567-b42e-ce106718ad70', gen_salt('bf')),
  now(), '{"provider":"email","providers":["email"]}', '{"full_name":"DevAtlas Seed"}',
  now(), now()
)
on conflict (id) do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Greenfield SaaS Bootstrap$body$,
  'greenfield-saas-bootstrap',
  $body$Scaffold a new SaaS product end-to-end: auth, billing-ready structure, and a deployable skeleton from a blank repo.$body$,
  'new_app',
  true,
  $body$You are a senior full-stack engineer bootstrapping a new SaaS product from an empty repository. Set up the project structure, authentication, a database schema for the core domain, and a deployable skeleton — a thin vertical slice that runs end-to-end, not a pile of unconnected scaffolding. Do not build the full feature set; the goal is a correct, deployable foundation others can build on.$body$,
  $body$Product: [ONE-SENTENCE DESCRIPTION OF WHAT THE SAAS DOES]. Target users: [WHO USES THIS]. Preferred stack: [FRAMEWORK, LANGUAGE, DATABASE — or 'no preference, recommend one']. Core domain objects: [THE 2-4 MAIN THINGS THE APP MANAGES, e.g. 'projects and tasks']. Auth requirements: [EMAIL/PASSWORD, OAUTH PROVIDERS, OR BOTH]. Hosting target: [VERCEL/AWS/OTHER].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A PRIOR PROJECT WITH A SIMILAR STRUCTURE YOU'D LIKE MIRRORED — e.g. a repo whose folder layout, auth setup, or deployment pipeline worked well]. If none, say so and the response should propose a structure from scratch.$body$,
  $body$[LINK: YOUR CHOSEN FRAMEWORK'S DOCS]. [LINK: YOUR CHOSEN DATABASE/AUTH PROVIDER'S DOCS]. [LINK: YOUR HOSTING PROVIDER'S DEPLOYMENT GUIDE].$body$,
  $body$A correct response includes: the project scaffold with a clear folder structure, a working auth flow (sign up, sign in, sign out), a first migration for the core domain objects, one deployable route/page proving the stack is wired together end-to-end, and a short README section on how to run it locally and deploy it.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['nextjs', 'supabase', 'typescript']::text[]), unnest(array['nextjs', 'supabase', 'typescript']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'greenfield-saas-bootstrap' and t.slug = any(array['nextjs', 'supabase', 'typescript']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Cross-Platform Mobile App Bootstrap$body$,
  'cross-platform-mobile-app-bootstrap',
  $body$Bootstrap a cross-platform mobile app with navigation, state management, and a CI pipeline in place from day one.$body$,
  'new_app',
  true,
  $body$You are a senior mobile engineer setting up a new cross-platform mobile app from scratch. Establish the navigation structure, a state-management pattern, and a CI pipeline that lints, type-checks, and runs tests on every push — before any real feature work begins, since retrofitting these later is expensive.$body$,
  $body$App purpose: [ONE-SENTENCE DESCRIPTION]. Target platforms: [IOS, ANDROID, OR BOTH]. Preferred framework: [REACT NATIVE / EXPO / OTHER — or 'no preference']. Initial screens needed: [LIST 3-5 SCREENS, e.g. 'onboarding, home feed, profile']. State management preference: [REDUX/ZUSTAND/CONTEXT/OTHER — or 'recommend one']. CI provider: [GITHUB ACTIONS/OTHER].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A MOBILE APP YOU'VE BUILT OR ADMIRE WHOSE NAVIGATION/STATE PATTERN SHOULD BE MIRRORED].$body$,
  $body$[LINK: YOUR CHOSEN FRAMEWORK'S DOCS, e.g. Expo or React Native]. [LINK: YOUR CI PROVIDER'S MOBILE-BUILD DOCS].$body$,
  $body$A correct response includes: the initialized project with navigation wired between the listed screens, a chosen state-management pattern with one working example (not just installed, actually used), a CI config file that runs lint/typecheck/test on push, and notes on how to run the app on a simulator/device.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['react-native', 'ci-cd']::text[]), unnest(array['react-native', 'ci-cd']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'cross-platform-mobile-app-bootstrap' and t.slug = any(array['react-native', 'ci-cd']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$CLI Tool From Scratch$body$,
  'cli-tool-from-scratch',
  $body$Build a command-line tool with proper argument parsing, help text, and a packaging setup ready to publish.$body$,
  'new_app',
  true,
  $body$You are a senior engineer building a new command-line tool from scratch. Implement proper argument/flag parsing, clear help text, sensible exit codes, and a packaging/build setup so the tool can be installed and run like any other CLI. Prioritize a good first-run experience: a user should be able to run `--help` and understand exactly what the tool does.$body$,
  $body$Tool purpose: [WHAT THE CLI DOES, ONE SENTENCE]. Commands/subcommands needed: [LIST THEM, e.g. 'init, build, deploy']. Language/runtime: [NODE/PYTHON/GO/OTHER]. Distribution target: [NPM/HOMEBREW/PYPI/OTHER]. Config file support needed: [YES/NO — AND WHAT FORMAT].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A CLI TOOL WHOSE UX (HELP TEXT, FLAG NAMING, OUTPUT FORMATTING) YOU WANT MIRRORED].$body$,
  $body$[LINK: YOUR CHOSEN ARG-PARSING LIBRARY'S DOCS]. [LINK: YOUR DISTRIBUTION TARGET'S PUBLISHING GUIDE, e.g. npm publish docs].$body$,
  $body$A correct response includes: working argument/flag parsing for every listed command, `--help` output that's actually useful, non-zero exit codes on failure with a clear error message, a packaging config ready for the stated distribution target, and at least one test covering the CLI's core command.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['typescript', 'testing']::text[]), unnest(array['typescript', 'testing']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'cli-tool-from-scratch' and t.slug = any(array['typescript', 'testing']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Full-Stack API + Frontend Starter$body$,
  'full-stack-api-frontend-starter',
  $body$Stand up a REST or GraphQL API alongside its frontend, sharing types end-to-end from a blank repo.$body$,
  'new_app',
  true,
  $body$You are a senior full-stack engineer setting up a new project with a separate API layer and frontend, sharing types between them so a change to the API's shape is a compile error in the frontend, not a runtime surprise. Stand up one real endpoint and the frontend view that consumes it, end-to-end, as proof the wiring works — not two disconnected halves.$body$,
  $body$App purpose: [ONE-SENTENCE DESCRIPTION]. API style: [REST OR GRAPHQL]. Backend framework: [FRAMEWORK — or 'recommend one']. Frontend framework: [FRAMEWORK — or 'recommend one']. First resource to model: [e.g. 'users' or 'posts']. Type-sharing approach: [MONOREPO WITH SHARED PACKAGE / CODEGEN / OTHER — or 'recommend one'].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A PRIOR PROJECT WITH A TYPE-SHARING SETUP YOU LIKED].$body$,
  $body$[LINK: YOUR API FRAMEWORK'S DOCS]. [LINK: YOUR FRONTEND FRAMEWORK'S DOCS]. [LINK: YOUR TYPE-SHARING TOOL'S DOCS, e.g. tRPC or GraphQL codegen].$body$,
  $body$A correct response includes: the monorepo/project structure, one working CRUD endpoint for the first resource, a frontend page that fetches and renders it with full type safety (no `any`), and a short explanation of how types stay in sync when the API shape changes.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['api', 'typescript', 'nextjs']::text[]), unnest(array['api', 'typescript', 'nextjs']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'full-stack-api-frontend-starter' and t.slug = any(array['api', 'typescript', 'nextjs']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Add Notification System$body$,
  'add-notification-system',
  $body$Add an in-app and email notification system with preferences, batching, and delivery tracking to an existing app.$body$,
  'module_feature',
  true,
  $body$You are a senior full-stack engineer adding a notification system to an existing application. Support both in-app and email notifications, let users configure per-type preferences, batch high-frequency notifications instead of spamming, and track delivery status. Integrate with the app's existing user and event model rather than inventing a parallel one.$body$,
  $body$Stack: [YOUR APP'S TECH STACK]. Database: [YOUR DATABASE + ORM]. Notification types needed: [LIST EVENTS THAT SHOULD NOTIFY, e.g. 'comment reply, mention, weekly digest']. Email provider: [YOUR EMAIL SENDING SERVICE, e.g. Resend/SendGrid]. Existing user/preferences model: [DESCRIBE, IF ANY].$body$,
  $body$[PASTE LINKS OR DESCRIPTIONS OF A NOTIFICATION SYSTEM YOU'VE BUILT OR SEEN THAT HANDLED BATCHING/PREFERENCES WELL].$body$,
  $body$[LINK: YOUR EMAIL PROVIDER'S API DOCS]. [LINK: YOUR DATABASE'S DOCS ON BACKGROUND JOBS OR QUEUES, IF RELEVANT].$body$,
  $body$A correct response includes: a schema for notifications and per-user preferences, an in-app notification feed (read/unread state), an email-sending path with a batching/digest strategy for high-frequency events, delivery-status tracking, and a note on how a new notification type gets added later.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['postgres', 'api', 'nextjs']::text[]), unnest(array['postgres', 'api', 'nextjs']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'add-notification-system' and t.slug = any(array['postgres', 'api', 'nextjs']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Add Role-Based Access Control (RBAC)$body$,
  'add-role-based-access-control-rbac',
  $body$Introduce roles, permissions, and route/UI gating to an app that currently treats all users the same.$body$,
  'module_feature',
  true,
  $body$You are a senior full-stack engineer. Implement role-based access control (RBAC) in an existing application. Add a roles/permissions model, gate both API routes and UI elements by role, and ensure the change is backward-compatible for existing users (who should default to the lowest-privilege role). Do not modify unrelated features.$body$,
  $body$Stack: [YOUR APP'S TECH STACK]. Database: [YOUR DATABASE + ORM]. Roles needed: [LIST ROLES, e.g. admin, editor, viewer]. Current auth system: [DESCRIBE YOUR AUTH SETUP]. Areas to gate: [LIST ROUTES/UI ELEMENTS THAT NEED RESTRICTING].$body$,
  $body$[PASTE LINKS OR DESCRIPTIONS OF 1-2 PRIOR PROJECTS WITH A SIMILAR PERMISSIONS MODEL, e.g. a repo with a working roles table or middleware you want mirrored].$body$,
  $body$[LINK: YOUR AUTH PROVIDER'S RBAC/CLAIMS DOCS]. [LINK: YOUR DATABASE'S ROW-LEVEL SECURITY DOCS, IF APPLICABLE].$body$,
  $body$A correct response includes: a migration adding the roles/permissions schema, middleware or a guard function checking role on every gated route, UI conditionally rendering restricted actions, a default role assigned to existing users, and a short note on how to promote/demote a user's role.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['auth', 'postgres', 'typescript']::text[]), unnest(array['auth', 'postgres', 'typescript']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'add-role-based-access-control-rbac' and t.slug = any(array['auth', 'postgres', 'typescript']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Add a Stripe Billing Module$body$,
  'add-a-stripe-billing-module',
  $body$Add subscription billing to an existing app: pricing tiers, checkout, webhooks, and access gating by plan.$body$,
  'module_feature',
  true,
  $body$You are a senior full-stack engineer implementing subscription billing with Stripe in an existing application. Add pricing-tier plans, a checkout flow, webhook handling that keeps the app's own subscription state in sync with Stripe (not just trusting the client), and feature/access gating based on plan. Treat the webhook handler as the source of truth for subscription state, not the checkout redirect.$body$,
  $body$Stack: [YOUR APP'S TECH STACK]. Existing user/auth model: [DESCRIBE YOUR AUTH SETUP]. Subscription tiers/pricing: [LIST TIERS AND WHAT EACH UNLOCKS]. Billing cadence: [MONTHLY/ANNUAL/BOTH]. Features to gate by plan: [LIST THEM].$body$,
  $body$[PASTE LINKS OR DESCRIPTIONS OF A PRIOR BILLING INTEGRATION YOU'VE SHIPPED OR A REPO WITH A WORKING STRIPE WEBHOOK HANDLER YOU WANT MIRRORED].$body$,
  $body$[LINK: STRIPE'S CHECKOUT/SUBSCRIPTIONS DOCS]. [LINK: STRIPE'S WEBHOOK SIGNATURE VERIFICATION DOCS].$body$,
  $body$A correct response includes: a schema change to track plan/subscription state, a checkout session creation endpoint, a signature-verified webhook handler covering subscription created/updated/canceled events, feature gating that reads from the app's own synced state (not a live Stripe call per request), and test coverage notes for the webhook handler.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['api', 'postgres', 'auth']::text[]), unnest(array['api', 'postgres', 'auth']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'add-a-stripe-billing-module' and t.slug = any(array['api', 'postgres', 'auth']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Add Search + Filters to an Existing Data Model$body$,
  'add-search-filters-to-existing-data-model',
  $body$Add free-text search combined with structured filters to an existing list view, backed by proper indexes.$body$,
  'module_feature',
  true,
  $body$You are a senior backend engineer adding search and filtering to an existing list view. Combine free-text search with structured filters (category, date range, status, etc. as applicable), back it with proper database indexes so it stays fast as data grows, and keep filter state in the URL so results are shareable and bookmarkable.$body$,
  $body$Stack: [YOUR APP'S TECH STACK]. Database: [YOUR DATABASE]. The data model being searched: [DESCRIBE THE TABLE/FIELDS, e.g. 'products: name, description, category, price']. Filters needed: [LIST THEM]. Expected data volume: [ROUGH ROW COUNT, NOW AND PROJECTED].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A SEARCH/FILTER IMPLEMENTATION YOU'VE BUILT THAT PERFORMED WELL AT SCALE].$body$,
  $body$[LINK: YOUR DATABASE'S FULL-TEXT SEARCH DOCS, e.g. Postgres tsvector/GIN indexes].$body$,
  $body$A correct response includes: the index(es) needed for the search/filter combination, a query (or RPC function) that applies free-text search and filters together correctly (AND semantics unless specified otherwise), URL-param-driven filter state on the frontend, and a note on expected query performance at the stated data volume.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['postgres', 'api']::text[]), unnest(array['postgres', 'api']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'add-search-filters-to-existing-data-model' and t.slug = any(array['postgres', 'api']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Root-Cause a Flaky Bug$body$,
  'root-cause-a-flaky-bug',
  $body$Systematically isolate and fix a test or feature that fails intermittently, with a reproducible root cause.$body$,
  'debugging',
  true,
  $body$You are a senior engineer debugging a flaky test or feature — one that fails intermittently rather than consistently. Do not patch around the symptom (e.g. adding a retry or a sleep) until you've identified the actual root cause. Form a hypothesis, verify it with evidence (logs, a minimal reproduction, or added instrumentation), then fix the real cause.$body$,
  $body$Stack: [YOUR APP'S TECH STACK]. What's flaky: [DESCRIBE THE TEST/FEATURE AND HOW OFTEN IT FAILS]. Failure symptom: [PASTE THE ERROR MESSAGE OR STACK TRACE]. Recent changes: [ANYTHING THAT CHANGED AROUND WHEN THE FLAKINESS STARTED, IF KNOWN]. Environment it happens in: [CI ONLY / LOCAL ONLY / BOTH].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A SIMILAR FLAKY-TEST ROOT CAUSE YOU'VE SEEN BEFORE, e.g. a race condition pattern that's shown up in this codebase before].$body$,
  $body$[LINK: YOUR TEST FRAMEWORK'S DOCS ON DEBUGGING FLAKY TESTS, IF ANY]. [LINK: YOUR CI PROVIDER'S RE-RUN/RETRY LOGS, IF RELEVANT].$body$,
  $body$A correct response includes: a clearly stated hypothesis for the root cause, evidence supporting it (not just a guess), a fix that addresses the actual cause (e.g. a race condition, shared state, timing assumption) rather than masking it, and a way to verify the fix — ideally a reproduction that reliably failed before and reliably passes after.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['testing', 'ci-cd']::text[]), unnest(array['testing', 'ci-cd']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'root-cause-a-flaky-bug' and t.slug = any(array['testing', 'ci-cd']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Diagnose a Production Performance Regression$body$,
  'diagnose-a-production-performance-regression',
  $body$Find and fix a performance regression in production using metrics, tracing, and targeted profiling.$body$,
  'debugging',
  true,
  $body$You are a senior engineer diagnosing a performance regression in production. Use available metrics and tracing to narrow down where time is being lost before proposing a fix — do not guess at optimizations without evidence. Once the bottleneck is identified, propose the smallest change that fixes it, and note how to confirm the fix worked in production.$body$,
  $body$Stack: [YOUR APP'S TECH STACK]. What got slower: [DESCRIBE THE ENDPOINT/PAGE/JOB AND THE SYMPTOM, e.g. 'p95 latency went from 200ms to 2s']. When it started: [TIMEFRAME, AND ANY DEPLOYS AROUND THEN]. Available observability tools: [e.g. 'CloudWatch, Datadog, application logs']. Traffic pattern: [DID TRAFFIC/DATA VOLUME CHANGE TOO?].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A SIMILAR PERFORMANCE ISSUE YOU'VE DIAGNOSED BEFORE IN THIS OR A SIMILAR SYSTEM].$body$,
  $body$[LINK: YOUR CLOUD PROVIDER'S MONITORING/TRACING DOCS, e.g. AWS X-Ray or CloudWatch]. [LINK: YOUR DATABASE'S QUERY-PROFILING DOCS, IF THE REGRESSION MIGHT BE A QUERY].$body$,
  $body$A correct response includes: a methodical narrowing-down process (not a shotgun list of possible causes), the identified bottleneck backed by metrics/traces, a targeted fix sized to the actual cause, and a concrete way to confirm the regression is resolved in production (a metric/dashboard to watch, not just 'it feels faster').$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['aws', 'api', 'testing']::text[]), unnest(array['aws', 'api', 'testing']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'diagnose-a-production-performance-regression' and t.slug = any(array['aws', 'api', 'testing']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Debug a Failing CI Suite$body$,
  'debug-a-failing-ci-suite',
  $body$Diagnose why CI is red — dependency drift, environment difference, or a genuine regression — and fix it correctly.$body$,
  'debugging',
  true,
  $body$You are a senior engineer debugging a CI pipeline that started failing. First determine whether this is a genuine code regression, an environment/dependency difference between CI and local, or a CI configuration problem — each needs a different fix. Do not disable or skip the failing check as a shortcut unless that is explicitly the right call and you say so explicitly.$body$,
  $body$CI provider: [e.g. GITHUB ACTIONS, CIRCLECI]. What's failing: [PASTE THE FAILING STEP'S NAME AND ERROR OUTPUT]. Does it fail locally too: [YES/NO/HAVEN'T TRIED]. Recent changes to the repo or CI config: [DESCRIBE, IF KNOWN]. Does it fail consistently or intermittently: [CONSISTENT/FLAKY — if flaky, this may be the 'Root-Cause a Flaky Bug' prompt instead].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A SIMILAR CI FAILURE (E.G. A LOCKFILE/DEPENDENCY MISMATCH) YOU'VE RESOLVED BEFORE].$body$,
  $body$[LINK: YOUR CI PROVIDER'S DOCS ON THE RELEVANT STEP, e.g. caching or matrix builds]. [LINK: YOUR PACKAGE MANAGER'S LOCKFILE DOCS, IF THIS IS A DEPENDENCY ISSUE].$body$,
  $body$A correct response includes: a clear diagnosis of which category the failure falls into (regression / environment drift / CI config), the specific root cause within that category, a fix, and — if the cause was an environment difference — a note on how to prevent CI and local from drifting again (e.g. pinning versions, matching Node/runtime versions).$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['ci-cd', 'testing']::text[]), unnest(array['ci-cd', 'testing']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'debug-a-failing-ci-suite' and t.slug = any(array['ci-cd', 'testing']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Investigate and Fix a Data Integrity Issue$body$,
  'investigate-and-fix-a-data-integrity-issue',
  $body$Track down how bad data got into the database, contain the damage, and fix both the data and its root cause.$body$,
  'debugging',
  true,
  $body$You are a senior engineer investigating a data integrity issue in production — records that are missing, duplicated, or inconsistent with each other. Find how the bad data was introduced before deciding how to clean it up; a cleanup script without a root-cause fix just needs to be run again later. Be explicit about blast radius: how many records are affected and how you'll verify the fix doesn't miss or over-correct any of them.$body$,
  $body$Stack: [YOUR APP'S TECH STACK]. Database: [YOUR DATABASE]. What's wrong with the data: [DESCRIBE THE INCONSISTENCY, e.g. 'orders with no matching customer_id']. Scale of the problem: [HOW MANY RECORDS, IF KNOWN]. Suspected cause: [ANY HYPOTHESIS, e.g. 'a migration that ran without a transaction'].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A SIMILAR DATA-INTEGRITY INCIDENT YOU'VE HANDLED BEFORE AND HOW IT WAS RESOLVED].$body$,
  $body$[LINK: YOUR DATABASE'S DOCS ON TRANSACTIONS/CONSTRAINTS, e.g. foreign keys or check constraints]. [LINK: YOUR APP'S MIGRATION TOOL'S DOCS, IF THE CAUSE MIGHT BE A MIGRATION].$body$,
  $body$A correct response includes: the confirmed root cause (not just a symptom description), a safe cleanup approach (ideally reversible, run inside a transaction, tested on a copy first), a constraint or code change that prevents the same corruption from happening again, and a note on how many records were affected and how that was verified.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['postgres', 'api']::text[]), unnest(array['postgres', 'api']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'investigate-and-fix-a-data-integrity-issue' and t.slug = any(array['postgres', 'api']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Responsive Dashboard from Design Spec$body$,
  'responsive-dashboard-from-design-spec',
  $body$Turn a design spec into a responsive, accessible dashboard UI with real data binding.$body$,
  'frontend',
  true,
  $body$You are a senior frontend engineer implementing a dashboard UI from a design spec. Build it responsive across mobile/tablet/desktop, accessible (semantic markup, keyboard navigation, sufficient contrast), and wired to real data rather than hardcoded placeholder content. Match the spec's layout and component states (loading, empty, error) exactly rather than approximating.$body$,
  $body$Stack: [YOUR FRONTEND FRAMEWORK + STYLING APPROACH]. Design spec: [PASTE A LINK TO THE DESIGN FILE/SCREENS, OR DESCRIBE THE LAYOUT IN DETAIL]. Data source: [WHERE THE DASHBOARD'S DATA COMES FROM — API ENDPOINT, HOOK, ETC.]. Breakpoints to support: [LIST THEM, e.g. 'mobile 375px, tablet 768px, desktop 1280px+'].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A DASHBOARD YOU'VE BUILT WITH A SIMILAR COMPONENT/STATE PATTERN YOU WANT MIRRORED].$body$,
  $body$[LINK: THE DESIGN SPEC/FIGMA FILE]. [LINK: YOUR COMPONENT LIBRARY'S DOCS, IF USING ONE].$body$,
  $body$A correct response includes: components matching the spec's layout at every listed breakpoint, loading/empty/error states for each data-driven section (not just the happy path), semantic HTML with keyboard-reachable interactive elements, and real data binding rather than static mock content left in place.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['react', 'typescript']::text[]), unnest(array['react', 'typescript']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'responsive-dashboard-from-design-spec' and t.slug = any(array['react', 'typescript']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Implement Complex Client-Side Form Validation$body$,
  'implement-complex-client-side-form-validation',
  $body$Build a multi-field form with interdependent validation rules, inline errors, and a good keyboard/a11y experience.$body$,
  'frontend',
  true,
  $body$You are a senior frontend engineer implementing a complex form with interdependent field validation (where one field's valid values depend on another's), inline per-field error messages, and a submit flow that surfaces errors clearly. Validate on blur, not just on submit, and don't block typing itself. Ensure the form is fully usable by keyboard and that error messages are announced to assistive technology.$body$,
  $body$Stack: [YOUR FRONTEND FRAMEWORK]. Form library preference: [e.g. REACT HOOK FORM, FORMIK, OR 'RECOMMEND ONE']. Fields and their validation rules: [LIST EACH FIELD AND ITS RULES, INCLUDING ANY CROSS-FIELD DEPENDENCIES]. Submit behavior: [WHAT HAPPENS ON SUCCESSFUL SUBMIT — API CALL, REDIRECT, ETC.].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A FORM WITH SIMILAR VALIDATION COMPLEXITY YOU'VE BUILT BEFORE].$body$,
  $body$[LINK: YOUR CHOSEN FORM LIBRARY'S DOCS]. [LINK: WCAG GUIDANCE ON ACCESSIBLE FORM ERROR MESSAGING].$body$,
  $body$A correct response includes: validation logic for every listed field and cross-field rule, inline error messages that appear on blur (not just on submit), a disabled or clearly-marked submit state while invalid, full keyboard operability, and error messages wired up with `aria-describedby`/`aria-invalid` so they're announced by screen readers.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['react', 'typescript']::text[]), unnest(array['react', 'typescript']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'implement-complex-client-side-form-validation' and t.slug = any(array['react', 'typescript']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Accessibility Audit and Remediation$body$,
  'accessibility-audit-and-remediation',
  $body$Audit an existing UI against WCAG, then fix the issues found — not just list them.$body$,
  'frontend',
  true,
  $body$You are a senior frontend engineer performing an accessibility audit of an existing UI against WCAG 2.1 AA, then fixing what you find. Go beyond automated-scanner-catchable issues (missing alt text, contrast) to also check keyboard operability, focus order, and screen-reader announcement of dynamic content. Prioritize fixes by real user impact, not by how easy each is to fix.$body$,
  $body$Stack: [YOUR FRONTEND FRAMEWORK]. Pages/components in scope: [LIST WHAT'S BEING AUDITED]. Known pain points, if any: [ANYTHING ALREADY FLAGGED BY USERS OR A PRIOR SCAN]. Target conformance level: [WCAG 2.1 AA — OR STATE A DIFFERENT TARGET].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A PRIOR ACCESSIBILITY REMEDIATION YOU'VE DONE, ESPECIALLY ANY REUSABLE FIXES LIKE A FOCUS-TRAP UTILITY].$body$,
  $body$[LINK: WCAG 2.1 SUCCESS CRITERIA]. [LINK: YOUR PREFERRED AUTOMATED SCANNER, e.g. axe-core, IF ONE SHOULD BE RUN FIRST].$body$,
  $body$A correct response includes: a prioritized list of issues found (with the specific WCAG criterion each violates), actual code fixes for each — not just recommendations — covering both automated-catchable issues and manual-only issues like focus order and dynamic-content announcements, and a note on how to verify each fix (e.g. which screen reader/keyboard-only pass to re-test with).$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['testing']::text[]), unnest(array['testing']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'accessibility-audit-and-remediation' and t.slug = any(array['testing']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Design and Implement a REST API$body$,
  'design-and-implement-a-rest-api',
  $body$Design and implement a REST API with proper resource modeling, validation, and auth from scratch.$body$,
  'backend',
  true,
  $body$You are a senior backend engineer designing and implementing a new REST API. Model resources properly (correct nouns, nesting, and HTTP verbs), validate input at the boundary, return consistent error shapes, and wire in authentication/authorization from the start rather than bolting it on later. Favor a small number of well-designed endpoints over a sprawling ad-hoc set.$body$,
  $body$Stack: [YOUR BACKEND FRAMEWORK + LANGUAGE]. Database: [YOUR DATABASE + ORM]. Resources to model: [LIST THE MAIN RESOURCES AND THEIR RELATIONSHIPS]. Auth requirements: [WHO CAN DO WHAT — PUBLIC READ? AUTHENTICATED WRITE? ROLES?]. Expected consumers: [WEB APP / MOBILE APP / THIRD-PARTY INTEGRATIONS].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF AN API YOU'VE DESIGNED BEFORE WHOSE RESOURCE MODELING OR ERROR-SHAPE CONVENTIONS YOU WANT MIRRORED].$body$,
  $body$[LINK: YOUR BACKEND FRAMEWORK'S DOCS]. [LINK: YOUR AUTH APPROACH'S DOCS, e.g. JWT or session-based auth].$body$,
  $body$A correct response includes: a resource/endpoint design (method + path for each), input validation on every write endpoint, a consistent error response shape across the API, auth/authorization enforcement matching the stated requirements, and a brief note on versioning or backward-compatibility strategy for future changes.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['api', 'postgres', 'auth']::text[]), unnest(array['api', 'postgres', 'auth']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'design-and-implement-a-rest-api' and t.slug = any(array['api', 'postgres', 'auth']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Add Background Job / Queue Processing$body$,
  'add-background-job-queue-processing',
  $body$Move slow or unreliable work off the request path into a queue, with retries and failure visibility.$body$,
  'backend',
  true,
  $body$You are a senior backend engineer moving slow or unreliable work (emails, file processing, third-party API calls) off the synchronous request path and into a background job queue. Implement retries with backoff for transient failures, a dead-letter path for jobs that fail permanently, and visibility into job status so failures don't go unnoticed.$body$,
  $body$Stack: [YOUR BACKEND FRAMEWORK]. Queue/job infrastructure: [e.g. SQS, BULLMQ+REDIS, OR 'RECOMMEND ONE']. Work to move to the background: [LIST THE SLOW/UNRELIABLE OPERATIONS]. Current behavior: [IS THIS WORK CURRENTLY DONE SYNCHRONOUSLY IN THE REQUEST? DESCRIBE]. Failure tolerance: [WHAT SHOULD HAPPEN IF A JOB FAILS PERMANENTLY — ALERT? RETRY FOREVER? DROP?].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF A QUEUE SETUP YOU'VE BUILT BEFORE WITH A RETRY/DEAD-LETTER PATTERN YOU WANT MIRRORED].$body$,
  $body$[LINK: YOUR CHOSEN QUEUE TECHNOLOGY'S DOCS, e.g. AWS SQS or BullMQ]. [LINK: YOUR MONITORING/ALERTING TOOL'S DOCS, FOR JOB-FAILURE VISIBILITY].$body$,
  $body$A correct response includes: the queue setup and job producer/consumer code, a retry-with-backoff strategy for transient failures, a dead-letter queue or equivalent for permanent failures, a way to observe job status (succeeded/failed/pending counts), and confirmation that the original synchronous code path was actually removed, not left running alongside the new queue.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['api', 'aws']::text[]), unnest(array['api', 'aws']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'add-background-job-queue-processing' and t.slug = any(array['api', 'aws']::text[])
on conflict do nothing;

insert into public.prompts (
  author_id, title, slug, description, category, is_published,
  base_instructions, fill_in_details_guidance, reference_projects_guidance,
  reference_links_guidance, expected_output_notes
)
values (
  '00000000-0000-0000-0000-000000000001',
  $body$Implement Rate Limiting and API Auth$body$,
  'implement-rate-limiting-and-api-auth',
  $body$Add request authentication and per-client rate limiting to an API that currently has neither.$body$,
  'backend',
  true,
  $body$You are a senior backend engineer adding authentication and rate limiting to an existing API. Implement a token-based auth scheme appropriate for the stated consumers, then add per-client rate limiting with clear `429` responses and standard rate-limit headers, so well-behaved clients can back off correctly instead of guessing.$body$,
  $body$Stack: [YOUR BACKEND FRAMEWORK]. API consumers: [WHO CALLS THIS API — INTERNAL SERVICES, THIRD-PARTY DEVELOPERS, ETC.]. Auth scheme preference: [API KEYS / OAUTH / JWT — OR 'RECOMMEND ONE']. Rate limit requirements: [REQUESTS PER MINUTE/HOUR, AND WHETHER LIMITS DIFFER BY PLAN/TIER]. Storage available for limit counters: [REDIS / IN-MEMORY / OTHER].$body$,
  $body$[PASTE A LINK OR DESCRIPTION OF AN AUTH/RATE-LIMITING IMPLEMENTATION YOU'VE SHIPPED BEFORE].$body$,
  $body$[LINK: YOUR CHOSEN AUTH SCHEME'S SPEC/DOCS]. [LINK: RFC 6585 / STANDARD RATE-LIMIT HEADER CONVENTIONS, e.g. `X-RateLimit-*` or `RateLimit-*`].$body$,
  $body$A correct response includes: the auth scheme implementation with credential issuance/validation, middleware enforcing it on protected routes, a rate-limiting implementation keyed per client (not globally), correct `429` responses with rate-limit headers on every response (not just when limited), and a note on how limits differ by tier if applicable.$body$
)
on conflict (slug) do nothing;

insert into public.tags (name, slug)
select unnest(array['api', 'auth']::text[]), unnest(array['api', 'auth']::text[])
on conflict (slug) do nothing;

insert into public.prompt_tags (prompt_id, tag_id)
select pr.id, t.id from public.prompts pr, public.tags t
where pr.slug = 'implement-rate-limiting-and-api-auth' and t.slug = any(array['api', 'auth']::text[])
on conflict do nothing;
