// Generates supabase/seed/prompts.sql from scripts/seed-data.ts, so the
// SQL mirror (used by `supabase db reset` for local dev) never drifts from
// scripts/seed-prompts.ts's content. Re-run this after editing seed-data.ts:
//   npx tsx scripts/generate-seed-sql.ts

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { SEED_PROMPTS } from "./seed-data";

const SEED_AUTHOR_ID = "00000000-0000-0000-0000-000000000001";
const SEED_AUTHOR_EMAIL = "seed@devatlas.internal";

// Dollar-quoted so apostrophes in prompt copy ("you'll", "don't") never
// need manual escaping.
function dq(value: string): string {
  return `$body$${value}$body$`;
}

function tagsArrayLiteral(tags: string[]): string {
  const items = tags.map((t) => `'${t.replace(/'/g, "''")}'`).join(", ");
  return `array[${items}]::text[]`;
}

const lines: string[] = [];

lines.push(
  "-- Generated by scripts/generate-seed-sql.ts from scripts/seed-data.ts.",
  "-- Applied automatically by `supabase db reset` for local development.",
  "-- Do not hand-edit — edit scripts/seed-data.ts and regenerate instead.",
  "",
  "-- Seed author: a system account every seed prompt is attributed to.",
  "-- Inserted directly into auth.users (standard local-seed pattern) so",
  "-- the handle_new_user() trigger creates the matching profiles row.",
  `insert into auth.users (`,
  `  instance_id, id, aud, role, email, encrypted_password,`,
  `  email_confirmed_at, raw_app_meta_data, raw_user_meta_data,`,
  `  created_at, updated_at`,
  `)`,
  `values (`,
  `  '00000000-0000-0000-0000-000000000000',`,
  `  '${SEED_AUTHOR_ID}',`,
  `  'authenticated', 'authenticated', '${SEED_AUTHOR_EMAIL}',`,
  `  crypt('${crypto.randomUUID()}', gen_salt('bf')),`,
  `  now(), '{"provider":"email","providers":["email"]}', '{"full_name":"DevAtlas Team"}',`,
  `  now(), now()`,
  `)`,
  `on conflict (id) do nothing;`,
  ""
);

for (const p of SEED_PROMPTS) {
  lines.push(
    `insert into public.prompts (`,
    `  author_id, title, slug, description, category, is_published,`,
    `  base_instructions, fill_in_details_guidance, reference_projects_guidance,`,
    `  reference_links_guidance, expected_output_notes`,
    `)`,
    `values (`,
    `  '${SEED_AUTHOR_ID}',`,
    `  ${dq(p.title)},`,
    `  '${p.slug}',`,
    `  ${dq(p.description)},`,
    `  '${p.category}',`,
    `  true,`,
    `  ${dq(p.base_instructions)},`,
    `  ${dq(p.fill_in_details_guidance)},`,
    `  ${dq(p.reference_projects_guidance)},`,
    `  ${dq(p.reference_links_guidance)},`,
    `  ${dq(p.expected_output_notes)}`,
    `)`,
    `on conflict (slug) do nothing;`,
    "",
    `insert into public.tags (name, slug)`,
    `select unnest(${tagsArrayLiteral(p.tags)}), unnest(${tagsArrayLiteral(p.tags)})`,
    `on conflict (slug) do nothing;`,
    "",
    `insert into public.prompt_tags (prompt_id, tag_id)`,
    `select pr.id, t.id from public.prompts pr, public.tags t`,
    `where pr.slug = '${p.slug}' and t.slug = any(${tagsArrayLiteral(p.tags)})`,
    `on conflict do nothing;`,
    ""
  );
}

const outPath = join(__dirname, "..", "supabase", "seed", "prompts.sql");
writeFileSync(outPath, lines.join("\n"));
console.log(`Wrote ${outPath} (${SEED_PROMPTS.length} prompts)`);
