// Source of truth for DevAtlas's 48 starter prompts. Both
// scripts/seed-prompts.ts (upserts via supabase-js) and
// supabase/seed/prompts.sql (generated by scripts/generate-seed-sql.ts,
// for `supabase db reset`) read from this file so the two never drift.
//
// Review rubric applied to every entry below: placeholders are bracketed
// consistently ([LIKE THIS]), expected_output_notes is specific enough to
// catch a lazy AI response, and tags are drawn from a shared, reused pool
// rather than one-off per prompt.

export interface SeedPrompt {
  title: string;
  slug: string;
  description: string;
  category: "new_app" | "module_feature" | "debugging" | "frontend" | "backend";
  tags: string[];
  base_instructions: string;
  fill_in_details_guidance: string;
  reference_projects_guidance: string;
  reference_links_guidance: string;
  expected_output_notes: string;
}

export const SEED_PROMPTS: SeedPrompt[] = [
  // ─── new_app (4) ────────────────────────────────────────────────────
  {
    title: "Greenfield SaaS Bootstrap",
    slug: "greenfield-saas-bootstrap",
    description:
      "Scaffold a new SaaS product end-to-end: auth, billing-ready structure, and a deployable skeleton from a blank repo.",
    category: "new_app",
    tags: ["nextjs", "supabase", "typescript"],
    base_instructions:
      "You are a senior full-stack engineer bootstrapping a new SaaS product from an empty repository. Set up the project structure, authentication, a database schema for the core domain, and a deployable skeleton — a thin vertical slice that runs end-to-end, not a pile of unconnected scaffolding. Do not build the full feature set; the goal is a correct, deployable foundation others can build on.",
    fill_in_details_guidance:
      "Product: [ONE-SENTENCE DESCRIPTION OF WHAT THE SAAS DOES]. Target users: [WHO USES THIS]. Preferred stack: [FRAMEWORK, LANGUAGE, DATABASE — or 'no preference, recommend one']. Core domain objects: [THE 2-4 MAIN THINGS THE APP MANAGES, e.g. 'projects and tasks']. Auth requirements: [EMAIL/PASSWORD, OAUTH PROVIDERS, OR BOTH]. Hosting target: [VERCEL/AWS/OTHER].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A PRIOR PROJECT WITH A SIMILAR STRUCTURE YOU'D LIKE MIRRORED — e.g. a repo whose folder layout, auth setup, or deployment pipeline worked well]. If none, say so and the response should propose a structure from scratch.",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN FRAMEWORK'S DOCS]. [LINK: YOUR CHOSEN DATABASE/AUTH PROVIDER'S DOCS]. [LINK: YOUR HOSTING PROVIDER'S DEPLOYMENT GUIDE].",
    expected_output_notes:
      "A correct response includes: the project scaffold with a clear folder structure, a working auth flow (sign up, sign in, sign out), a first migration for the core domain objects, one deployable route/page proving the stack is wired together end-to-end, and a short README section on how to run it locally and deploy it.",
  },
  {
    title: "Cross-Platform Mobile App Bootstrap",
    slug: "cross-platform-mobile-app-bootstrap",
    description:
      "Bootstrap a cross-platform mobile app with navigation, state management, and a CI pipeline in place from day one.",
    category: "new_app",
    tags: ["react-native", "ci-cd"],
    base_instructions:
      "You are a senior mobile engineer setting up a new cross-platform mobile app from scratch. Establish the navigation structure, a state-management pattern, and a CI pipeline that lints, type-checks, and runs tests on every push — before any real feature work begins, since retrofitting these later is expensive.",
    fill_in_details_guidance:
      "App purpose: [ONE-SENTENCE DESCRIPTION]. Target platforms: [IOS, ANDROID, OR BOTH]. Preferred framework: [REACT NATIVE / EXPO / OTHER — or 'no preference']. Initial screens needed: [LIST 3-5 SCREENS, e.g. 'onboarding, home feed, profile']. State management preference: [REDUX/ZUSTAND/CONTEXT/OTHER — or 'recommend one']. CI provider: [GITHUB ACTIONS/OTHER].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A MOBILE APP YOU'VE BUILT OR ADMIRE WHOSE NAVIGATION/STATE PATTERN SHOULD BE MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN FRAMEWORK'S DOCS, e.g. Expo or React Native]. [LINK: YOUR CI PROVIDER'S MOBILE-BUILD DOCS].",
    expected_output_notes:
      "A correct response includes: the initialized project with navigation wired between the listed screens, a chosen state-management pattern with one working example (not just installed, actually used), a CI config file that runs lint/typecheck/test on push, and notes on how to run the app on a simulator/device.",
  },
  {
    title: "CLI Tool From Scratch",
    slug: "cli-tool-from-scratch",
    description:
      "Build a command-line tool with proper argument parsing, help text, and a packaging setup ready to publish.",
    category: "new_app",
    tags: ["typescript", "testing"],
    base_instructions:
      "You are a senior engineer building a new command-line tool from scratch. Implement proper argument/flag parsing, clear help text, sensible exit codes, and a packaging/build setup so the tool can be installed and run like any other CLI. Prioritize a good first-run experience: a user should be able to run `--help` and understand exactly what the tool does.",
    fill_in_details_guidance:
      "Tool purpose: [WHAT THE CLI DOES, ONE SENTENCE]. Commands/subcommands needed: [LIST THEM, e.g. 'init, build, deploy']. Language/runtime: [NODE/PYTHON/GO/OTHER]. Distribution target: [NPM/HOMEBREW/PYPI/OTHER]. Config file support needed: [YES/NO — AND WHAT FORMAT].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A CLI TOOL WHOSE UX (HELP TEXT, FLAG NAMING, OUTPUT FORMATTING) YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN ARG-PARSING LIBRARY'S DOCS]. [LINK: YOUR DISTRIBUTION TARGET'S PUBLISHING GUIDE, e.g. npm publish docs].",
    expected_output_notes:
      "A correct response includes: working argument/flag parsing for every listed command, `--help` output that's actually useful, non-zero exit codes on failure with a clear error message, a packaging config ready for the stated distribution target, and at least one test covering the CLI's core command.",
  },
  {
    title: "Full-Stack API + Frontend Starter",
    slug: "full-stack-api-frontend-starter",
    description:
      "Stand up a REST or GraphQL API alongside its frontend, sharing types end-to-end from a blank repo.",
    category: "new_app",
    tags: ["api", "typescript", "nextjs"],
    base_instructions:
      "You are a senior full-stack engineer setting up a new project with a separate API layer and frontend, sharing types between them so a change to the API's shape is a compile error in the frontend, not a runtime surprise. Stand up one real endpoint and the frontend view that consumes it, end-to-end, as proof the wiring works — not two disconnected halves.",
    fill_in_details_guidance:
      "App purpose: [ONE-SENTENCE DESCRIPTION]. API style: [REST OR GRAPHQL]. Backend framework: [FRAMEWORK — or 'recommend one']. Frontend framework: [FRAMEWORK — or 'recommend one']. First resource to model: [e.g. 'users' or 'posts']. Type-sharing approach: [MONOREPO WITH SHARED PACKAGE / CODEGEN / OTHER — or 'recommend one'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A PRIOR PROJECT WITH A TYPE-SHARING SETUP YOU LIKED].",
    reference_links_guidance:
      "[LINK: YOUR API FRAMEWORK'S DOCS]. [LINK: YOUR FRONTEND FRAMEWORK'S DOCS]. [LINK: YOUR TYPE-SHARING TOOL'S DOCS, e.g. tRPC or GraphQL codegen].",
    expected_output_notes:
      "A correct response includes: the monorepo/project structure, one working CRUD endpoint for the first resource, a frontend page that fetches and renders it with full type safety (no `any`), and a short explanation of how types stay in sync when the API shape changes.",
  },

  // ─── module_feature (4) ─────────────────────────────────────────────
  {
    title: "Add Notification System",
    slug: "add-notification-system",
    description:
      "Add an in-app and email notification system with preferences, batching, and delivery tracking to an existing app.",
    category: "module_feature",
    tags: ["postgres", "api", "nextjs"],
    base_instructions:
      "You are a senior full-stack engineer adding a notification system to an existing application. Support both in-app and email notifications, let users configure per-type preferences, batch high-frequency notifications instead of spamming, and track delivery status. Integrate with the app's existing user and event model rather than inventing a parallel one.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Database: [YOUR DATABASE + ORM]. Notification types needed: [LIST EVENTS THAT SHOULD NOTIFY, e.g. 'comment reply, mention, weekly digest']. Email provider: [YOUR EMAIL SENDING SERVICE, e.g. Resend/SendGrid]. Existing user/preferences model: [DESCRIBE, IF ANY].",
    reference_projects_guidance:
      "[PASTE LINKS OR DESCRIPTIONS OF A NOTIFICATION SYSTEM YOU'VE BUILT OR SEEN THAT HANDLED BATCHING/PREFERENCES WELL].",
    reference_links_guidance:
      "[LINK: YOUR EMAIL PROVIDER'S API DOCS]. [LINK: YOUR DATABASE'S DOCS ON BACKGROUND JOBS OR QUEUES, IF RELEVANT].",
    expected_output_notes:
      "A correct response includes: a schema for notifications and per-user preferences, an in-app notification feed (read/unread state), an email-sending path with a batching/digest strategy for high-frequency events, delivery-status tracking, and a note on how a new notification type gets added later.",
  },
  {
    title: "Add Role-Based Access Control (RBAC)",
    slug: "add-role-based-access-control-rbac",
    description:
      "Introduce roles, permissions, and route/UI gating to an app that currently treats all users the same.",
    category: "module_feature",
    tags: ["auth", "postgres", "typescript"],
    base_instructions:
      "You are a senior full-stack engineer. Implement role-based access control (RBAC) in an existing application. Add a roles/permissions model, gate both API routes and UI elements by role, and ensure the change is backward-compatible for existing users (who should default to the lowest-privilege role). Do not modify unrelated features.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Database: [YOUR DATABASE + ORM]. Roles needed: [LIST ROLES, e.g. admin, editor, viewer]. Current auth system: [DESCRIBE YOUR AUTH SETUP]. Areas to gate: [LIST ROUTES/UI ELEMENTS THAT NEED RESTRICTING].",
    reference_projects_guidance:
      "[PASTE LINKS OR DESCRIPTIONS OF 1-2 PRIOR PROJECTS WITH A SIMILAR PERMISSIONS MODEL, e.g. a repo with a working roles table or middleware you want mirrored].",
    reference_links_guidance:
      "[LINK: YOUR AUTH PROVIDER'S RBAC/CLAIMS DOCS]. [LINK: YOUR DATABASE'S ROW-LEVEL SECURITY DOCS, IF APPLICABLE].",
    expected_output_notes:
      "A correct response includes: a migration adding the roles/permissions schema, middleware or a guard function checking role on every gated route, UI conditionally rendering restricted actions, a default role assigned to existing users, and a short note on how to promote/demote a user's role.",
  },
  {
    title: "Add a Stripe Billing Module",
    slug: "add-a-stripe-billing-module",
    description:
      "Add subscription billing to an existing app: pricing tiers, checkout, webhooks, and access gating by plan.",
    category: "module_feature",
    tags: ["api", "postgres", "auth"],
    base_instructions:
      "You are a senior full-stack engineer implementing subscription billing with Stripe in an existing application. Add pricing-tier plans, a checkout flow, webhook handling that keeps the app's own subscription state in sync with Stripe (not just trusting the client), and feature/access gating based on plan. Treat the webhook handler as the source of truth for subscription state, not the checkout redirect.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Existing user/auth model: [DESCRIBE YOUR AUTH SETUP]. Subscription tiers/pricing: [LIST TIERS AND WHAT EACH UNLOCKS]. Billing cadence: [MONTHLY/ANNUAL/BOTH]. Features to gate by plan: [LIST THEM].",
    reference_projects_guidance:
      "[PASTE LINKS OR DESCRIPTIONS OF A PRIOR BILLING INTEGRATION YOU'VE SHIPPED OR A REPO WITH A WORKING STRIPE WEBHOOK HANDLER YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: STRIPE'S CHECKOUT/SUBSCRIPTIONS DOCS]. [LINK: STRIPE'S WEBHOOK SIGNATURE VERIFICATION DOCS].",
    expected_output_notes:
      "A correct response includes: a schema change to track plan/subscription state, a checkout session creation endpoint, a signature-verified webhook handler covering subscription created/updated/canceled events, feature gating that reads from the app's own synced state (not a live Stripe call per request), and test coverage notes for the webhook handler.",
  },
  {
    title: "Add Search + Filters to an Existing Data Model",
    slug: "add-search-filters-to-existing-data-model",
    description:
      "Add free-text search combined with structured filters to an existing list view, backed by proper indexes.",
    category: "module_feature",
    tags: ["postgres", "api"],
    base_instructions:
      "You are a senior backend engineer adding search and filtering to an existing list view. Combine free-text search with structured filters (category, date range, status, etc. as applicable), back it with proper database indexes so it stays fast as data grows, and keep filter state in the URL so results are shareable and bookmarkable.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Database: [YOUR DATABASE]. The data model being searched: [DESCRIBE THE TABLE/FIELDS, e.g. 'products: name, description, category, price']. Filters needed: [LIST THEM]. Expected data volume: [ROUGH ROW COUNT, NOW AND PROJECTED].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SEARCH/FILTER IMPLEMENTATION YOU'VE BUILT THAT PERFORMED WELL AT SCALE].",
    reference_links_guidance:
      "[LINK: YOUR DATABASE'S FULL-TEXT SEARCH DOCS, e.g. Postgres tsvector/GIN indexes].",
    expected_output_notes:
      "A correct response includes: the index(es) needed for the search/filter combination, a query (or RPC function) that applies free-text search and filters together correctly (AND semantics unless specified otherwise), URL-param-driven filter state on the frontend, and a note on expected query performance at the stated data volume.",
  },

  // ─── debugging (4) ──────────────────────────────────────────────────
  {
    title: "Root-Cause a Flaky Bug",
    slug: "root-cause-a-flaky-bug",
    description:
      "Systematically isolate and fix a test or feature that fails intermittently, with a reproducible root cause.",
    category: "debugging",
    tags: ["testing", "ci-cd"],
    base_instructions:
      "You are a senior engineer debugging a flaky test or feature — one that fails intermittently rather than consistently. Do not patch around the symptom (e.g. adding a retry or a sleep) until you've identified the actual root cause. Form a hypothesis, verify it with evidence (logs, a minimal reproduction, or added instrumentation), then fix the real cause.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. What's flaky: [DESCRIBE THE TEST/FEATURE AND HOW OFTEN IT FAILS]. Failure symptom: [PASTE THE ERROR MESSAGE OR STACK TRACE]. Recent changes: [ANYTHING THAT CHANGED AROUND WHEN THE FLAKINESS STARTED, IF KNOWN]. Environment it happens in: [CI ONLY / LOCAL ONLY / BOTH].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR FLAKY-TEST ROOT CAUSE YOU'VE SEEN BEFORE, e.g. a race condition pattern that's shown up in this codebase before].",
    reference_links_guidance:
      "[LINK: YOUR TEST FRAMEWORK'S DOCS ON DEBUGGING FLAKY TESTS, IF ANY]. [LINK: YOUR CI PROVIDER'S RE-RUN/RETRY LOGS, IF RELEVANT].",
    expected_output_notes:
      "A correct response includes: a clearly stated hypothesis for the root cause, evidence supporting it (not just a guess), a fix that addresses the actual cause (e.g. a race condition, shared state, timing assumption) rather than masking it, and a way to verify the fix — ideally a reproduction that reliably failed before and reliably passes after.",
  },
  {
    title: "Diagnose a Production Performance Regression",
    slug: "diagnose-a-production-performance-regression",
    description:
      "Find and fix a performance regression in production using metrics, tracing, and targeted profiling.",
    category: "debugging",
    tags: ["aws", "api", "testing"],
    base_instructions:
      "You are a senior engineer diagnosing a performance regression in production. Use available metrics and tracing to narrow down where time is being lost before proposing a fix — do not guess at optimizations without evidence. Once the bottleneck is identified, propose the smallest change that fixes it, and note how to confirm the fix worked in production.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. What got slower: [DESCRIBE THE ENDPOINT/PAGE/JOB AND THE SYMPTOM, e.g. 'p95 latency went from 200ms to 2s']. When it started: [TIMEFRAME, AND ANY DEPLOYS AROUND THEN]. Available observability tools: [e.g. 'CloudWatch, Datadog, application logs']. Traffic pattern: [DID TRAFFIC/DATA VOLUME CHANGE TOO?].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR PERFORMANCE ISSUE YOU'VE DIAGNOSED BEFORE IN THIS OR A SIMILAR SYSTEM].",
    reference_links_guidance:
      "[LINK: YOUR CLOUD PROVIDER'S MONITORING/TRACING DOCS, e.g. AWS X-Ray or CloudWatch]. [LINK: YOUR DATABASE'S QUERY-PROFILING DOCS, IF THE REGRESSION MIGHT BE A QUERY].",
    expected_output_notes:
      "A correct response includes: a methodical narrowing-down process (not a shotgun list of possible causes), the identified bottleneck backed by metrics/traces, a targeted fix sized to the actual cause, and a concrete way to confirm the regression is resolved in production (a metric/dashboard to watch, not just 'it feels faster').",
  },
  {
    title: "Debug a Failing CI Suite",
    slug: "debug-a-failing-ci-suite",
    description:
      "Diagnose why CI is red — dependency drift, environment difference, or a genuine regression — and fix it correctly.",
    category: "debugging",
    tags: ["ci-cd", "testing"],
    base_instructions:
      "You are a senior engineer debugging a CI pipeline that started failing. First determine whether this is a genuine code regression, an environment/dependency difference between CI and local, or a CI configuration problem — each needs a different fix. Do not disable or skip the failing check as a shortcut unless that is explicitly the right call and you say so explicitly.",
    fill_in_details_guidance:
      "CI provider: [e.g. GITHUB ACTIONS, CIRCLECI]. What's failing: [PASTE THE FAILING STEP'S NAME AND ERROR OUTPUT]. Does it fail locally too: [YES/NO/HAVEN'T TRIED]. Recent changes to the repo or CI config: [DESCRIBE, IF KNOWN]. Does it fail consistently or intermittently: [CONSISTENT/FLAKY — if flaky, this may be the 'Root-Cause a Flaky Bug' prompt instead].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR CI FAILURE (E.G. A LOCKFILE/DEPENDENCY MISMATCH) YOU'VE RESOLVED BEFORE].",
    reference_links_guidance:
      "[LINK: YOUR CI PROVIDER'S DOCS ON THE RELEVANT STEP, e.g. caching or matrix builds]. [LINK: YOUR PACKAGE MANAGER'S LOCKFILE DOCS, IF THIS IS A DEPENDENCY ISSUE].",
    expected_output_notes:
      "A correct response includes: a clear diagnosis of which category the failure falls into (regression / environment drift / CI config), the specific root cause within that category, a fix, and — if the cause was an environment difference — a note on how to prevent CI and local from drifting again (e.g. pinning versions, matching Node/runtime versions).",
  },
  {
    title: "Investigate and Fix a Data Integrity Issue",
    slug: "investigate-and-fix-a-data-integrity-issue",
    description:
      "Track down how bad data got into the database, contain the damage, and fix both the data and its root cause.",
    category: "debugging",
    tags: ["postgres", "api"],
    base_instructions:
      "You are a senior engineer investigating a data integrity issue in production — records that are missing, duplicated, or inconsistent with each other. Find how the bad data was introduced before deciding how to clean it up; a cleanup script without a root-cause fix just needs to be run again later. Be explicit about blast radius: how many records are affected and how you'll verify the fix doesn't miss or over-correct any of them.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Database: [YOUR DATABASE]. What's wrong with the data: [DESCRIBE THE INCONSISTENCY, e.g. 'orders with no matching customer_id']. Scale of the problem: [HOW MANY RECORDS, IF KNOWN]. Suspected cause: [ANY HYPOTHESIS, e.g. 'a migration that ran without a transaction'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR DATA-INTEGRITY INCIDENT YOU'VE HANDLED BEFORE AND HOW IT WAS RESOLVED].",
    reference_links_guidance:
      "[LINK: YOUR DATABASE'S DOCS ON TRANSACTIONS/CONSTRAINTS, e.g. foreign keys or check constraints]. [LINK: YOUR APP'S MIGRATION TOOL'S DOCS, IF THE CAUSE MIGHT BE A MIGRATION].",
    expected_output_notes:
      "A correct response includes: the confirmed root cause (not just a symptom description), a safe cleanup approach (ideally reversible, run inside a transaction, tested on a copy first), a constraint or code change that prevents the same corruption from happening again, and a note on how many records were affected and how that was verified.",
  },

  // ─── frontend (3) ───────────────────────────────────────────────────
  {
    title: "Responsive Dashboard from Design Spec",
    slug: "responsive-dashboard-from-design-spec",
    description:
      "Turn a design spec into a responsive, accessible dashboard UI with real data binding.",
    category: "frontend",
    tags: ["react", "typescript"],
    base_instructions:
      "You are a senior frontend engineer implementing a dashboard UI from a design spec. Build it responsive across mobile/tablet/desktop, accessible (semantic markup, keyboard navigation, sufficient contrast), and wired to real data rather than hardcoded placeholder content. Match the spec's layout and component states (loading, empty, error) exactly rather than approximating.",
    fill_in_details_guidance:
      "Stack: [YOUR FRONTEND FRAMEWORK + STYLING APPROACH]. Design spec: [PASTE A LINK TO THE DESIGN FILE/SCREENS, OR DESCRIBE THE LAYOUT IN DETAIL]. Data source: [WHERE THE DASHBOARD'S DATA COMES FROM — API ENDPOINT, HOOK, ETC.]. Breakpoints to support: [LIST THEM, e.g. 'mobile 375px, tablet 768px, desktop 1280px+'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A DASHBOARD YOU'VE BUILT WITH A SIMILAR COMPONENT/STATE PATTERN YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: THE DESIGN SPEC/FIGMA FILE]. [LINK: YOUR COMPONENT LIBRARY'S DOCS, IF USING ONE].",
    expected_output_notes:
      "A correct response includes: components matching the spec's layout at every listed breakpoint, loading/empty/error states for each data-driven section (not just the happy path), semantic HTML with keyboard-reachable interactive elements, and real data binding rather than static mock content left in place.",
  },
  {
    title: "Implement Complex Client-Side Form Validation",
    slug: "implement-complex-client-side-form-validation",
    description:
      "Build a multi-field form with interdependent validation rules, inline errors, and a good keyboard/a11y experience.",
    category: "frontend",
    tags: ["react", "typescript"],
    base_instructions:
      "You are a senior frontend engineer implementing a complex form with interdependent field validation (where one field's valid values depend on another's), inline per-field error messages, and a submit flow that surfaces errors clearly. Validate on blur, not just on submit, and don't block typing itself. Ensure the form is fully usable by keyboard and that error messages are announced to assistive technology.",
    fill_in_details_guidance:
      "Stack: [YOUR FRONTEND FRAMEWORK]. Form library preference: [e.g. REACT HOOK FORM, FORMIK, OR 'RECOMMEND ONE']. Fields and their validation rules: [LIST EACH FIELD AND ITS RULES, INCLUDING ANY CROSS-FIELD DEPENDENCIES]. Submit behavior: [WHAT HAPPENS ON SUCCESSFUL SUBMIT — API CALL, REDIRECT, ETC.].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A FORM WITH SIMILAR VALIDATION COMPLEXITY YOU'VE BUILT BEFORE].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN FORM LIBRARY'S DOCS]. [LINK: WCAG GUIDANCE ON ACCESSIBLE FORM ERROR MESSAGING].",
    expected_output_notes:
      "A correct response includes: validation logic for every listed field and cross-field rule, inline error messages that appear on blur (not just on submit), a disabled or clearly-marked submit state while invalid, full keyboard operability, and error messages wired up with `aria-describedby`/`aria-invalid` so they're announced by screen readers.",
  },
  {
    title: "Accessibility Audit and Remediation",
    slug: "accessibility-audit-and-remediation",
    description:
      "Audit an existing UI against WCAG, then fix the issues found — not just list them.",
    category: "frontend",
    tags: ["testing"],
    base_instructions:
      "You are a senior frontend engineer performing an accessibility audit of an existing UI against WCAG 2.1 AA, then fixing what you find. Go beyond automated-scanner-catchable issues (missing alt text, contrast) to also check keyboard operability, focus order, and screen-reader announcement of dynamic content. Prioritize fixes by real user impact, not by how easy each is to fix.",
    fill_in_details_guidance:
      "Stack: [YOUR FRONTEND FRAMEWORK]. Pages/components in scope: [LIST WHAT'S BEING AUDITED]. Known pain points, if any: [ANYTHING ALREADY FLAGGED BY USERS OR A PRIOR SCAN]. Target conformance level: [WCAG 2.1 AA — OR STATE A DIFFERENT TARGET].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A PRIOR ACCESSIBILITY REMEDIATION YOU'VE DONE, ESPECIALLY ANY REUSABLE FIXES LIKE A FOCUS-TRAP UTILITY].",
    reference_links_guidance:
      "[LINK: WCAG 2.1 SUCCESS CRITERIA]. [LINK: YOUR PREFERRED AUTOMATED SCANNER, e.g. axe-core, IF ONE SHOULD BE RUN FIRST].",
    expected_output_notes:
      "A correct response includes: a prioritized list of issues found (with the specific WCAG criterion each violates), actual code fixes for each — not just recommendations — covering both automated-catchable issues and manual-only issues like focus order and dynamic-content announcements, and a note on how to verify each fix (e.g. which screen reader/keyboard-only pass to re-test with).",
  },

  // ─── backend (3) ────────────────────────────────────────────────────
  {
    title: "Design and Implement a REST API",
    slug: "design-and-implement-a-rest-api",
    description:
      "Design and implement a REST API with proper resource modeling, validation, and auth from scratch.",
    category: "backend",
    tags: ["api", "postgres", "auth"],
    base_instructions:
      "You are a senior backend engineer designing and implementing a new REST API. Model resources properly (correct nouns, nesting, and HTTP verbs), validate input at the boundary, return consistent error shapes, and wire in authentication/authorization from the start rather than bolting it on later. Favor a small number of well-designed endpoints over a sprawling ad-hoc set.",
    fill_in_details_guidance:
      "Stack: [YOUR BACKEND FRAMEWORK + LANGUAGE]. Database: [YOUR DATABASE + ORM]. Resources to model: [LIST THE MAIN RESOURCES AND THEIR RELATIONSHIPS]. Auth requirements: [WHO CAN DO WHAT — PUBLIC READ? AUTHENTICATED WRITE? ROLES?]. Expected consumers: [WEB APP / MOBILE APP / THIRD-PARTY INTEGRATIONS].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN API YOU'VE DESIGNED BEFORE WHOSE RESOURCE MODELING OR ERROR-SHAPE CONVENTIONS YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR BACKEND FRAMEWORK'S DOCS]. [LINK: YOUR AUTH APPROACH'S DOCS, e.g. JWT or session-based auth].",
    expected_output_notes:
      "A correct response includes: a resource/endpoint design (method + path for each), input validation on every write endpoint, a consistent error response shape across the API, auth/authorization enforcement matching the stated requirements, and a brief note on versioning or backward-compatibility strategy for future changes.",
  },
  {
    title: "Add Background Job / Queue Processing",
    slug: "add-background-job-queue-processing",
    description:
      "Move slow or unreliable work off the request path into a queue, with retries and failure visibility.",
    category: "backend",
    tags: ["api", "aws"],
    base_instructions:
      "You are a senior backend engineer moving slow or unreliable work (emails, file processing, third-party API calls) off the synchronous request path and into a background job queue. Implement retries with backoff for transient failures, a dead-letter path for jobs that fail permanently, and visibility into job status so failures don't go unnoticed.",
    fill_in_details_guidance:
      "Stack: [YOUR BACKEND FRAMEWORK]. Queue/job infrastructure: [e.g. SQS, BULLMQ+REDIS, OR 'RECOMMEND ONE']. Work to move to the background: [LIST THE SLOW/UNRELIABLE OPERATIONS]. Current behavior: [IS THIS WORK CURRENTLY DONE SYNCHRONOUSLY IN THE REQUEST? DESCRIBE]. Failure tolerance: [WHAT SHOULD HAPPEN IF A JOB FAILS PERMANENTLY — ALERT? RETRY FOREVER? DROP?].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A QUEUE SETUP YOU'VE BUILT BEFORE WITH A RETRY/DEAD-LETTER PATTERN YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN QUEUE TECHNOLOGY'S DOCS, e.g. AWS SQS or BullMQ]. [LINK: YOUR MONITORING/ALERTING TOOL'S DOCS, FOR JOB-FAILURE VISIBILITY].",
    expected_output_notes:
      "A correct response includes: the queue setup and job producer/consumer code, a retry-with-backoff strategy for transient failures, a dead-letter queue or equivalent for permanent failures, a way to observe job status (succeeded/failed/pending counts), and confirmation that the original synchronous code path was actually removed, not left running alongside the new queue.",
  },
  {
    title: "Implement Rate Limiting and API Auth",
    slug: "implement-rate-limiting-and-api-auth",
    description:
      "Add request authentication and per-client rate limiting to an API that currently has neither.",
    category: "backend",
    tags: ["api", "auth"],
    base_instructions:
      "You are a senior backend engineer adding authentication and rate limiting to an existing API. Implement a token-based auth scheme appropriate for the stated consumers, then add per-client rate limiting with clear `429` responses and standard rate-limit headers, so well-behaved clients can back off correctly instead of guessing.",
    fill_in_details_guidance:
      "Stack: [YOUR BACKEND FRAMEWORK]. API consumers: [WHO CALLS THIS API — INTERNAL SERVICES, THIRD-PARTY DEVELOPERS, ETC.]. Auth scheme preference: [API KEYS / OAUTH / JWT — OR 'RECOMMEND ONE']. Rate limit requirements: [REQUESTS PER MINUTE/HOUR, AND WHETHER LIMITS DIFFER BY PLAN/TIER]. Storage available for limit counters: [REDIS / IN-MEMORY / OTHER].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN AUTH/RATE-LIMITING IMPLEMENTATION YOU'VE SHIPPED BEFORE].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN AUTH SCHEME'S SPEC/DOCS]. [LINK: RFC 6585 / STANDARD RATE-LIMIT HEADER CONVENTIONS, e.g. `X-RateLimit-*` or `RateLimit-*`].",
    expected_output_notes:
      "A correct response includes: the auth scheme implementation with credential issuance/validation, middleware enforcing it on protected routes, a rate-limiting implementation keyed per client (not globally), correct `429` responses with rate-limit headers on every response (not just when limited), and a note on how limits differ by tier if applicable.",
  },

  // ─── new_app (+6, 10 total) ─────────────────────────────────────────
  {
    title: "Real-Time Chat Application Bootstrap",
    slug: "realtime-chat-app-bootstrap",
    description:
      "Bootstrap a real-time chat app from scratch: message delivery, presence, and reconnect handling wired end-to-end.",
    category: "new_app",
    tags: ["websockets", "typescript", "postgres"],
    base_instructions:
      "You are a senior full-stack engineer bootstrapping a real-time chat application from an empty repository. Stand up message persistence, a WebSocket (or equivalent real-time) transport, online-presence tracking, and reconnect/resume handling so a dropped connection doesn't lose or duplicate messages. Prove the transport works end-to-end with one real conversation thread, not a mocked demo.",
    fill_in_details_guidance:
      "Product: [ONE-SENTENCE DESCRIPTION, e.g. '1:1 and group chat for a support tool']. Preferred stack: [FRAMEWORK, REAL-TIME LIBRARY — e.g. Supabase Realtime, Socket.IO, Pusher — OR 'recommend one']. Database: [YOUR DATABASE]. Message features needed: [e.g. 'read receipts, typing indicators, attachments — list what applies']. Expected concurrent users: [ROUGH SCALE, IF KNOWN].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A REAL-TIME APP YOU'VE BUILT WHOSE RECONNECT/PRESENCE HANDLING WORKED WELL].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN REAL-TIME TRANSPORT'S DOCS]. [LINK: YOUR DATABASE'S DOCS ON THE REAL-TIME/CHANGE-FEED FEATURE, IF USING ONE].",
    expected_output_notes:
      "A correct response includes: a message schema with delivery/read state, a working real-time transport wired to one real conversation thread, presence tracking (online/offline, and typing if requested), reconnect logic that resyncs missed messages instead of silently dropping them, and a note on how message ordering is guaranteed under concurrent sends.",
  },
  {
    title: "Browser Extension From Scratch",
    slug: "browser-extension-from-scratch",
    description:
      "Build a browser extension with a background service worker, content script, and popup UI wired together correctly.",
    category: "new_app",
    tags: ["typescript", "testing"],
    base_instructions:
      "You are a senior engineer building a browser extension (Manifest V3) from scratch. Set up the background service worker, any content scripts, and the popup/options UI, with correct message-passing between them — this is where most extension bugs live, so be explicit about which context each piece of code runs in and how they communicate. Request the minimum permissions the stated functionality actually needs.",
    fill_in_details_guidance:
      "Extension purpose: [WHAT IT DOES, ONE SENTENCE]. Target browser(s): [CHROME/FIREFOX/BOTH — Manifest V3 compatibility]. Pages it needs to interact with: [SPECIFIC SITES, OR 'all sites']. Permissions likely needed: [e.g. 'storage, activeTab, scripting — or unsure, ask']. Build tooling preference: [e.g. Vite/CRXJS — or 'recommend one'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN EXTENSION WITH A SIMILAR CONTENT-SCRIPT/BACKGROUND MESSAGING PATTERN YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: CHROME/FIREFOX MANIFEST V3 DOCS]. [LINK: YOUR BUILD TOOL'S EXTENSION-PACKAGING DOCS, IF USING ONE].",
    expected_output_notes:
      "A correct response includes: a valid Manifest V3 manifest requesting only the necessary permissions, a background service worker, a content script (if needed) with correct message-passing to the background/popup, a working popup UI, and a note on how to load the unpacked extension locally for testing.",
  },
  {
    title: "E-Commerce Storefront Bootstrap",
    slug: "ecommerce-storefront-bootstrap",
    description:
      "Stand up a storefront skeleton: product catalog, cart, and a checkout flow ready to wire to a payment provider.",
    category: "new_app",
    tags: ["nextjs", "postgres", "api"],
    base_instructions:
      "You are a senior full-stack engineer bootstrapping an e-commerce storefront from scratch. Build the product catalog schema and listing/detail pages, a persistent cart (survives refresh, and ideally login), and a checkout flow structured to plug into a payment provider next — get the state machine and data model right even if payment itself is stubbed. Handle inventory/stock correctly: don't let two carts oversell the last unit without at least flagging it.",
    fill_in_details_guidance:
      "Store type: [WHAT'S BEING SOLD, ONE SENTENCE]. Stack: [FRAMEWORK, DATABASE]. Payment provider (even if stubbed for now): [e.g. Stripe — or 'undecided']. Cart persistence requirement: [GUEST CART / MUST BE LOGGED IN / BOTH]. Inventory tracking needed: [YES/NO, AND HOW STRICT — e.g. 'hard stock limit' vs 'soft, backorder allowed'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A STOREFRONT WHOSE CART/CHECKOUT STATE MACHINE YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN PAYMENT PROVIDER'S DOCS, EVEN IF INTEGRATING LATER]. [LINK: YOUR FRAMEWORK'S DOCS].",
    expected_output_notes:
      "A correct response includes: a product/variant/inventory schema, catalog listing and detail pages backed by real data, a cart that persists correctly per the stated requirement, a checkout flow structured for a payment provider to plug into, and explicit handling (not silence) around what happens when stock runs out mid-checkout.",
  },
  {
    title: "Internal Admin / Back-Office Tool Bootstrap",
    slug: "internal-admin-tool-bootstrap",
    description:
      "Bootstrap an internal admin tool for staff to manage the app's data, with auth gating from day one.",
    category: "new_app",
    tags: ["react", "postgres", "auth"],
    base_instructions:
      "You are a senior full-stack engineer bootstrapping an internal admin/back-office tool for staff to view and manage the main application's data. Gate the entire tool behind staff-only auth from the start (never ship an admin tool with a TODO to add auth later), build data tables with sort/filter/pagination for the core entities, and make destructive actions (delete, bulk-edit) require explicit confirmation.",
    fill_in_details_guidance:
      "Main app it's administering: [ONE-SENTENCE DESCRIPTION]. Entities staff need to manage: [LIST THEM, e.g. 'users, orders, support tickets']. Staff auth approach: [SEPARATE ADMIN LOGIN / REUSE MAIN APP AUTH WITH A ROLE CHECK]. Actions needed beyond viewing: [e.g. 'edit user role, refund an order, ban a user — list them'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN INTERNAL TOOL WITH A DATA-TABLE/ACTIONS PATTERN YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR AUTH PROVIDER'S DOCS FOR ROLE-GATING]. [LINK: A DATA-TABLE LIBRARY'S DOCS, IF USING ONE, e.g. TanStack Table].",
    expected_output_notes:
      "A correct response includes: the entire tool gated behind a staff-only check (not just hidden nav), data tables for each listed entity with working sort/filter/pagination, confirmation dialogs on every destructive action, and an audit trail (who did what, when) for actions that mutate other users' data.",
  },
  {
    title: "Content / Docs Site Bootstrap",
    slug: "content-docs-site-bootstrap",
    description:
      "Stand up a statically-generated content or documentation site with a content pipeline that's easy to add pages to.",
    category: "new_app",
    tags: ["nextjs", "typescript"],
    base_instructions:
      "You are a senior frontend engineer bootstrapping a statically-generated content or documentation site from scratch. Set up the content pipeline (MDX or a headless CMS, per what's specified), navigation/sidebar generation that stays in sync with actual content instead of being hand-maintained, and search. Optimize for a low-friction authoring experience — adding a new page should not require touching routing code.",
    fill_in_details_guidance:
      "Site purpose: [DOCS / BLOG / MARKETING CONTENT — ONE SENTENCE]. Content source: [MDX FILES IN-REPO / HEADLESS CMS — NAME IT, OR 'recommend one']. Framework: [e.g. Next.js, Astro — or 'recommend one']. Search requirement: [YES/NO, AND WHETHER CLIENT-SIDE (e.g. FlexSearch) OR HOSTED (e.g. Algolia) IS PREFERRED]. Initial page count/structure: [ROUGH OUTLINE, IF KNOWN].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A DOCS/CONTENT SITE WITH A NAVIGATION/AUTHORING PATTERN YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR FRAMEWORK'S DOCS]. [LINK: YOUR CHOSEN SEARCH SOLUTION'S DOCS, IF ANY].",
    expected_output_notes:
      "A correct response includes: the content pipeline wired up end-to-end (adding a new content file produces a new page with zero routing-code changes), auto-generated navigation that reflects actual content, working search if requested, and static generation confirmed (not accidentally forced dynamic).",
  },
  {
    title: "Multi-Tenant SaaS Bootstrap",
    slug: "multi-tenant-saas-bootstrap",
    description:
      "Bootstrap a multi-tenant SaaS with tenant isolation built into the data model and every query from day one.",
    category: "new_app",
    tags: ["postgres", "auth", "security"],
    base_instructions:
      "You are a senior full-stack engineer bootstrapping a multi-tenant SaaS product from an empty repository. Bake tenant isolation into the data model and every query from the start (a shared `tenant_id` column plus row-level security or an equivalent enforced-at-the-database layer, not just app-code discipline) — retrofitting isolation after data exists across tenants is high-risk. Prove isolation with a concrete test: two tenants' data, one query, confirm no cross-tenant leakage.",
    fill_in_details_guidance:
      "Product: [ONE-SENTENCE DESCRIPTION]. Tenancy model: [ONE ORG PER TENANT / ONE USER PER TENANT / OTHER]. Stack: [FRAMEWORK, DATABASE]. Isolation approach preference: [SHARED SCHEMA WITH ROW-LEVEL SECURITY / SCHEMA-PER-TENANT / DATABASE-PER-TENANT — or 'recommend one for the expected scale']. Expected tenant count and scale: [ROUGH NUMBERS, IF KNOWN].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A MULTI-TENANT SYSTEM WHOSE ISOLATION APPROACH YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR DATABASE'S ROW-LEVEL SECURITY / MULTI-TENANCY DOCS]. [LINK: YOUR AUTH PROVIDER'S DOCS ON ORG/TENANT MODELING, IF RELEVANT].",
    expected_output_notes:
      "A correct response includes: the tenant data model, isolation enforced at the database layer (not only in application code), a first working end-to-end tenant-scoped feature, and an explicit test or query demonstrating that a second tenant's data is genuinely unreachable — not just unlinked in the UI.",
  },

  // ─── module_feature (+6, 10 total) ──────────────────────────────────
  {
    title: "Add Real-Time Collaboration",
    slug: "add-real-time-collaboration",
    description:
      "Add live presence and real-time synced updates (e.g. multiplayer editing or live dashboards) to an existing view.",
    category: "module_feature",
    tags: ["websockets", "react", "postgres"],
    base_instructions:
      "You are a senior full-stack engineer adding real-time collaboration to an existing view — live presence (who else is here) and synced updates when data changes, without requiring a manual refresh. Handle the conflict case explicitly: what happens when two users change the same thing near-simultaneously. Degrade gracefully if the real-time connection drops (fall back to the last-known state, don't crash the view).",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Real-time transport available/preferred: [e.g. Supabase Realtime, Pusher, custom WebSocket server — or 'recommend one']. The view being made collaborative: [DESCRIBE IT, e.g. 'a shared kanban board']. Conflict scenario to handle: [e.g. 'two users drag the same card at once — describe the desired resolution, or ask for a recommendation']. Presence info needed: [e.g. 'avatar + cursor position', or just 'online/offline'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A COLLABORATIVE FEATURE YOU'VE BUILT WITH A CONFLICT-RESOLUTION APPROACH YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR REAL-TIME TRANSPORT'S DOCS]. [LINK: A CRDT OR OPERATIONAL-TRANSFORM LIBRARY'S DOCS, IF THE CONFLICT CASE NEEDS ONE].",
    expected_output_notes:
      "A correct response includes: presence tracking wired to the view, live-synced updates without a manual refresh, an explicit, stated resolution for the near-simultaneous-edit conflict case (not silently last-write-wins unless that was the actual decision), and graceful behavior when the connection drops and reconnects.",
  },
  {
    title: "Add File Upload and Storage Pipeline",
    slug: "add-file-upload-storage-pipeline",
    description:
      "Add secure file/image upload to an existing app: validation, storage, and access-controlled serving.",
    category: "module_feature",
    tags: ["api", "aws", "postgres"],
    base_instructions:
      "You are a senior full-stack engineer adding a file/image upload pipeline to an existing application. Validate file type and size before accepting an upload (not just at the client, since that's trivially bypassed), store files in object storage rather than the database, and serve them with access control matching the app's existing permission model — don't make every uploaded file publicly guessable by URL unless that's explicitly intended.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Storage backend: [e.g. S3, Supabase Storage, Cloudinary — or 'recommend one']. What's being uploaded: [e.g. 'user avatars and document attachments — list allowed types and max size']. Access model needed: [PUBLIC / PRIVATE-PER-OWNER / PRIVATE-PER-TEAM]. Processing needed on upload: [e.g. 'image resizing/thumbnails' — or 'none'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN UPLOAD PIPELINE YOU'VE BUILT WITH A VALIDATION/ACCESS-CONTROL PATTERN YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR STORAGE BACKEND'S DOCS, INCLUDING SIGNED-URL/ACCESS-CONTROL SECTION]. [LINK: AN IMAGE-PROCESSING LIBRARY'S DOCS, IF RESIZING IS NEEDED].",
    expected_output_notes:
      "A correct response includes: server-side validation of file type/size (not just client-side), storage in object storage with a schema linking files to their owning record, access-controlled serving matching the stated model (signed URLs or an authorization check, not public-by-default), and any requested processing (e.g. thumbnails) actually wired into the upload flow.",
  },
  {
    title: "Add Multi-Factor Authentication (MFA)",
    slug: "add-multi-factor-authentication-mfa",
    description:
      "Add TOTP-based multi-factor authentication to an existing app, including enrollment, verification, and recovery.",
    category: "module_feature",
    tags: ["auth", "security"],
    base_instructions:
      "You are a senior full-stack engineer adding multi-factor authentication (TOTP-based, e.g. authenticator apps) to an existing application. Implement enrollment (QR code + verification before it's activated, so a typo'd setup can't lock a user out), the login-time challenge, and a recovery path (backup codes) for when the user loses their authenticator device — MFA without a recovery path turns a security feature into a support-ticket generator.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Auth provider/library: [YOUR CURRENT AUTH SETUP — e.g. Supabase Auth, custom, Auth0]. MFA requirement: [OPTIONAL PER-USER / MANDATORY FOR ALL / MANDATORY FOR ADMIN ROLES ONLY]. Recovery approach preference: [BACKUP CODES / SMS FALLBACK / SUPPORT-ASSISTED RESET — or 'recommend one'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN MFA IMPLEMENTATION YOU'VE SHIPPED OR SEEN WITH A GOOD ENROLLMENT/RECOVERY UX].",
    reference_links_guidance:
      "[LINK: YOUR AUTH PROVIDER'S MFA/TOTP DOCS]. [LINK: RFC 6238 (TOTP), IF IMPLEMENTING FROM SCRATCH RATHER THAN VIA A PROVIDER].",
    expected_output_notes:
      "A correct response includes: enrollment with QR code generation and a verify-before-activate step, the login-time TOTP challenge wired into the existing auth flow, single-use backup/recovery codes generated at enrollment, and a note on what happens if a user is mid-login when MFA is turned on for their account.",
  },
  {
    title: "Add Internationalization (i18n)",
    slug: "add-internationalization-i18n",
    description:
      "Add multi-language support to an existing app: string extraction, a translation pipeline, and locale-aware formatting.",
    category: "module_feature",
    tags: ["react", "i18n"],
    base_instructions:
      "You are a senior frontend engineer adding internationalization to an existing application that currently has hardcoded English strings. Extract strings into a translation-key structure, wire up an i18n library with locale detection and switching, and make sure dates/numbers/currency are locale-formatted, not just the copy text. Don't stop at the happy-path screens — cover error messages and empty states too, since those are the ones teams usually forget.",
    fill_in_details_guidance:
      "Stack: [YOUR FRONTEND FRAMEWORK]. i18n library preference: [e.g. next-intl, react-i18next — or 'recommend one']. Target locales: [LIST THEM, e.g. 'en, es, ja']. Locale detection/switching requirement: [AUTO-DETECT FROM BROWSER / URL-BASED (e.g. /es/...) / USER PREFERENCE SETTING]. Scope: [WHICH SCREENS/FLOWS NEED TRANSLATING FIRST, IF NOT THE WHOLE APP].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN I18N SETUP YOU'VE BUILT WITH A STRING-EXTRACTION/TRANSLATION-KEY CONVENTION YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN I18N LIBRARY'S DOCS]. [LINK: THE INTL/ECMA-402 DOCS FOR LOCALE-AWARE DATE/NUMBER FORMATTING].",
    expected_output_notes:
      "A correct response includes: hardcoded strings replaced with translation keys in the stated scope (including error/empty states, not just happy-path copy), a working locale switcher, translation files for every target locale (even if placeholder-translated), and locale-aware date/number/currency formatting, not just swapped-out prose.",
  },
  {
    title: "Add a Feature Flag / Gradual Rollout System",
    slug: "add-feature-flag-gradual-rollout-system",
    description:
      "Add a feature-flagging system so new features can ship to a subset of users and be killed instantly if something breaks.",
    category: "module_feature",
    tags: ["api", "postgres"],
    base_instructions:
      "You are a senior backend engineer adding a feature-flag system to an existing application, so new features can be enabled for a subset of users (by percentage, user list, or attribute) and disabled instantly without a deploy if something goes wrong. Make flag evaluation fast (no per-request round trip to an external service on the hot path unless that's explicitly acceptable) and make the kill-switch path genuinely instant — not gated behind the same deploy pipeline as the feature itself.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Approach preference: [BUILD IN-HOUSE (SIMPLE) / USE A PROVIDER, e.g. LaunchDarkly, Statsig, Unleash]. Targeting needed: [PERCENTAGE ROLLOUT / SPECIFIC USER LIST / USER ATTRIBUTE, e.g. 'beta testers' — list what's needed]. Where flags need to be checked: [e.g. 'backend API and frontend UI, or just one'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A FEATURE-FLAG SETUP YOU'VE BUILT OR USED WITH A TARGETING/KILL-SWITCH PATTERN YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN FLAG PROVIDER'S DOCS, IF USING ONE]. [LINK: YOUR CACHING LAYER'S DOCS, IF FLAGS NEED TO BE EVALUATED FAST AND OFTEN].",
    expected_output_notes:
      "A correct response includes: a flag schema/config supporting the stated targeting rules, an evaluation path fast enough for the hot path it's used on, a way to flip a flag off that takes effect immediately (no redeploy required), and a note on how flag state is cached/invalidated so the kill-switch is actually instant.",
  },
  {
    title: "Add Audit Logging for Compliance",
    slug: "add-audit-logging-for-compliance",
    description:
      "Add an immutable audit trail of who changed what and when, for the actions that need one for compliance or trust.",
    category: "module_feature",
    tags: ["postgres", "security", "api"],
    base_instructions:
      "You are a senior backend engineer adding audit logging to an existing application for compliance and internal trust. Record who performed an action, what changed (before/after where applicable), when, and from where (IP/user agent if relevant) — for the specific actions that need it, not indiscriminately every request. Make the audit log append-only and inaccessible to normal application code paths that could tamper with it.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Database: [YOUR DATABASE]. Actions that need auditing: [LIST THEM, e.g. 'role changes, data deletion, billing plan changes']. Retention requirement: [HOW LONG AUDIT RECORDS MUST BE KEPT, IF KNOWN]. Who needs to view the audit log: [ADMINS ONLY / THE AFFECTED USER TOO / EXTERNAL COMPLIANCE EXPORT].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN AUDIT-LOGGING IMPLEMENTATION YOU'VE BUILT WITH A SCHEMA/TAMPER-RESISTANCE APPROACH YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR DATABASE'S DOCS ON APPEND-ONLY/IMMUTABLE TABLE PATTERNS OR TRIGGERS]. [LINK: RELEVANT COMPLIANCE STANDARD'S AUDIT REQUIREMENTS, e.g. SOC 2, IF APPLICABLE].",
    expected_output_notes:
      "A correct response includes: an audit log schema capturing actor, action, before/after state, and timestamp, hooks on every listed action that write to it, database-level protection against normal app code updating/deleting audit rows, and a view/export path for whoever is stated as needing to read the log.",
  },

  // ─── debugging (+6, 10 total) ────────────────────────────────────────
  {
    title: "Diagnose and Fix a Memory Leak",
    slug: "diagnose-and-fix-a-memory-leak",
    description:
      "Confirm, isolate, and fix a memory leak using heap snapshots or profiling rather than guessing at the cause.",
    category: "debugging",
    tags: ["performance", "testing"],
    base_instructions:
      "You are a senior engineer diagnosing a suspected memory leak. Confirm it's real (memory growing unboundedly over time, not just normal working-set fluctuation) using a heap snapshot, profiler, or memory-over-time metric before proposing a fix. Identify the specific retained-reference pattern (e.g. an uncleared interval, an event listener never removed, a growing cache with no eviction) rather than a vague 'reduce memory usage' fix.",
    fill_in_details_guidance:
      "Stack/runtime: [YOUR APP'S TECH STACK, e.g. Node.js, browser, a specific mobile runtime]. Symptom: [DESCRIBE HOW MEMORY GROWTH SHOWS UP, e.g. 'server RSS climbs steadily over 24h until OOM']. Available tooling: [e.g. 'Chrome DevTools heap snapshots', '--inspect + clinic.js', 'nothing set up yet']. Suspected area, if any: [A COMPONENT/MODULE YOU SUSPECT, OR 'unknown'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR MEMORY-LEAK PATTERN YOU'VE DIAGNOSED BEFORE IN THIS OR A SIMILAR CODEBASE].",
    reference_links_guidance:
      "[LINK: YOUR RUNTIME'S MEMORY-PROFILING DOCS, e.g. Chrome DevTools Memory panel or Node --inspect]. [LINK: YOUR HOSTING/MONITORING PROVIDER'S MEMORY-METRICS DOCS].",
    expected_output_notes:
      "A correct response includes: confirmation the leak is real with evidence (a snapshot diff or memory-over-time graph, not a guess), the specific retained-reference pattern identified as the cause, a fix that removes the actual leak (not a periodic-restart workaround unless explicitly requested as a stopgap), and a way to verify memory now plateaus under sustained load.",
  },
  {
    title: "Track Down an N+1 Query Problem",
    slug: "track-down-an-n-plus-1-query-problem",
    description:
      "Find and fix an N+1 query pattern using query logs or an ORM query counter, not guesswork.",
    category: "debugging",
    tags: ["postgres", "performance", "api"],
    base_instructions:
      "You are a senior backend engineer diagnosing a suspected N+1 query problem — one query to fetch a list, then one additional query per item to fetch related data. Confirm it with actual query logs or an ORM's query-count tooling before fixing, then resolve it with eager loading, a join, or a batching/dataloader pattern appropriate to the stack — pick the fix that fits the access pattern rather than reflexively eager-loading everything.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. ORM/query layer: [e.g. Prisma, Drizzle, raw SQL]. The slow endpoint/view: [DESCRIBE IT AND WHAT DATA IT RETURNS]. Evidence so far: [PASTE QUERY LOGS OR A QUERY COUNT, IF ALREADY GATHERED — OR 'none yet, need help gathering it']. Relationship shape causing the suspected N+1: [e.g. 'posts, each needing its author and comment count'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR N+1 PATTERN YOU'VE FIXED BEFORE IN THIS CODEBASE, e.g. a reusable eager-loading helper].",
    reference_links_guidance:
      "[LINK: YOUR ORM'S DOCS ON EAGER LOADING/INCLUDES]. [LINK: YOUR DATABASE'S DOCS ON EXPLAIN/QUERY LOGGING, e.g. Postgres `EXPLAIN ANALYZE`].",
    expected_output_notes:
      "A correct response includes: confirmation of the N+1 pattern with an actual query count or log (before), the fix applied (join, eager-load, or batching, matched to the access pattern), the resulting query count after the fix (should be O(1) or O(log n), not O(n)), and a note on how to catch this pattern regressing again (e.g. a query-count assertion in tests).",
  },
  {
    title: "Debug a Race Condition in Concurrent Code",
    slug: "debug-a-race-condition-in-concurrent-code",
    description:
      "Isolate a race condition between concurrent operations and fix it with proper synchronization, not a sleep/retry hack.",
    category: "debugging",
    tags: ["testing", "api"],
    base_instructions:
      "You are a senior engineer debugging a race condition — a bug that depends on the relative timing of two or more concurrent operations. Identify the specific shared state or resource both operations touch and the exact interleaving that causes the bug, then fix it with proper synchronization (a lock, a transaction with the right isolation level, an atomic operation, or a queue serializing the conflicting work) — not a `sleep()`, retry loop, or other timing-dependent workaround that just makes the bug rarer.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. The concurrent operations involved: [DESCRIBE BOTH/ALL OPERATIONS AND WHAT SHARED STATE THEY TOUCH]. Symptom: [WHAT GOES WRONG, e.g. 'duplicate orders created', 'a counter ends up wrong under load']. How it's been reproduced so far: [DESCRIBE, OR 'only seen in production, not yet reproduced locally'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR RACE CONDITION YOU'VE FIXED BEFORE, e.g. a locking pattern already used elsewhere in this codebase].",
    reference_links_guidance:
      "[LINK: YOUR DATABASE'S DOCS ON TRANSACTION ISOLATION LEVELS OR ADVISORY LOCKS, IF THE RACE IS DATABASE-LEVEL]. [LINK: YOUR RUNTIME'S CONCURRENCY-PRIMITIVES DOCS, e.g. mutexes or atomics, IF APPLICATION-LEVEL].",
    expected_output_notes:
      "A correct response includes: the exact interleaving that causes the bug (stated explicitly, not just 'it's a race condition'), a fix using real synchronization appropriate to where the race occurs (app-level lock, DB transaction/isolation level, or atomic operation), confirmation the fix doesn't just narrow the timing window, and — ideally — a test that reliably reproduces the race before the fix and passes after.",
  },
  {
    title: "Diagnose Intermittent Third-Party API Failures",
    slug: "diagnose-intermittent-third-party-api-failures",
    description:
      "Determine whether intermittent failures calling a third-party API are your bug, their instability, or a rate limit — and fix accordingly.",
    category: "debugging",
    tags: ["api", "testing"],
    base_instructions:
      "You are a senior engineer diagnosing intermittent failures when calling a third-party API. Distinguish between three different root causes — a bug on your side (bad payload, timeout too short, connection pool exhaustion), genuine instability on their side, or you hitting a rate limit — since each needs a different fix. Once diagnosed, implement the right mitigation: retries with backoff for transient failures, a circuit breaker if their instability is sustained, or respecting their stated rate limits if that's the cause.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Third-party API involved: [NAME IT]. Failure pattern: [DESCRIBE — e.g. 'fails roughly 1 in 20 calls, mostly 502s', PASTE ANY ERROR RESPONSES/HEADERS RECEIVED]. Current retry/timeout behavior, if any: [DESCRIBE]. Their documented rate limits, if known: [PASTE OR 'not sure, need to check'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR THIRD-PARTY-API RELIABILITY ISSUE YOU'VE HANDLED BEFORE AND HOW].",
    reference_links_guidance:
      "[LINK: THE THIRD-PARTY API'S DOCS, ESPECIALLY RATE LIMITS AND ERROR-CODE MEANINGS]. [LINK: THEIR STATUS PAGE, IF THEY HAVE ONE, TO CROSS-CHECK TIMING].",
    expected_output_notes:
      "A correct response includes: a diagnosis backed by evidence (error codes/headers/timing, not a guess) of which of the three categories the failures fall into, the specific mitigation matched to that category (not retries-for-everything as a blanket fix), confirmation the mitigation doesn't make a genuine rate-limit problem worse, and a note on how to tell the difference again if it recurs.",
  },
  {
    title: "Bisect a Regression to Its Introducing Commit",
    slug: "bisect-a-regression-to-its-introducing-commit",
    description:
      "Use git bisect (or an equivalent binary search) to find the exact commit that introduced a regression, then fix it.",
    category: "debugging",
    tags: ["ci-cd", "testing"],
    base_instructions:
      "You are a senior engineer tracking down a regression whose cause isn't obvious from the symptom alone. Use `git bisect` (or an equivalent binary search over deploys/versions if the history isn't git-bisectable) with a reliable pass/fail check at each step, to find the exact commit that introduced it — don't jump straight to guessing based on 'what changed recently' if the range of candidate commits is more than a handful. Once found, explain why that commit caused the regression before fixing it, since the fix should address the actual mechanism, not just revert blindly.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. The regression: [DESCRIBE THE SYMPTOM AND WHEN IT WAS FIRST NOTICED]. Known-good and known-bad reference points: [A COMMIT/TAG/DATE THAT DEFINITELY WORKED, AND ONE THAT DEFINITELY DOESN'T]. A reliable pass/fail check: [A TEST, SCRIPT, OR MANUAL STEP THAT CAN CONFIRM GOOD/BAD AT ANY GIVEN COMMIT — this is required for bisect to work].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR BISECT-FOUND REGRESSION IN THIS CODEBASE, IF ANY, FOR CONTEXT ON HOW CHANGES HERE TEND TO CAUSE REGRESSIONS].",
    reference_links_guidance:
      "[LINK: GIT BISECT DOCUMENTATION]. [LINK: YOUR CI PROVIDER'S DOCS ON RUNNING A SPECIFIC HISTORICAL COMMIT/BUILD, IF THE CHECK NEEDS TO RUN IN CI RATHER THAN LOCALLY].",
    expected_output_notes:
      "A correct response includes: the exact introducing commit identified via bisection (not a hunch), a clear explanation of the mechanism by which that commit caused the regression, a fix addressing that mechanism (a targeted fix or an informed revert, stated explicitly which), and — if the pass/fail check didn't already exist as an automated test — a suggestion to add one so this regression can't silently reintroduce itself.",
  },
  {
    title: "Diagnose Database Lock Contention / Deadlocks",
    slug: "diagnose-database-lock-contention-deadlocks",
    description:
      "Identify the queries and lock ordering causing contention or deadlocks, then fix the access pattern that causes them.",
    category: "debugging",
    tags: ["postgres", "performance"],
    base_instructions:
      "You are a senior backend engineer diagnosing database lock contention or deadlocks. Use the database's own lock/deadlock diagnostics (not application-level guessing) to identify which queries are holding and waiting on which locks, and in what order — a deadlock specifically requires two transactions acquiring the same locks in a different order. Fix the actual access pattern (consistent lock ordering, shorter transactions, a less restrictive isolation level, or `SELECT ... FOR UPDATE SKIP LOCKED` where appropriate) rather than adding a blind retry-on-deadlock wrapper as the only fix.",
    fill_in_details_guidance:
      "Database: [YOUR DATABASE, e.g. Postgres]. Symptom: [DESCRIBE — e.g. 'random `deadlock detected` errors under load', 'queries pile up waiting on a lock during peak traffic']. Transactions/queries suspected of being involved: [DESCRIBE THE OPERATIONS THAT RUN CONCURRENTLY AND TOUCH THE SAME ROWS/TABLES]. Diagnostics already available: [e.g. deadlock log output, `pg_locks` query results — PASTE IF AVAILABLE].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR LOCK-CONTENTION ISSUE YOU'VE RESOLVED BEFORE IN THIS OR A SIMILAR SYSTEM].",
    reference_links_guidance:
      "[LINK: YOUR DATABASE'S DOCS ON LOCK MONITORING AND DEADLOCK LOGGING, e.g. Postgres `pg_locks`/`log_lock_waits`]. [LINK: YOUR DATABASE'S DOCS ON TRANSACTION ISOLATION LEVELS].",
    expected_output_notes:
      "A correct response includes: the specific queries/transactions and lock acquisition order identified as the cause (from real diagnostics, not speculation), a fix that changes the access pattern itself (consistent ordering, shorter transaction scope, or an appropriate locking primitive), confirmation the fix doesn't just reduce the odds without eliminating the possibility, and a note on how contention is monitored going forward.",
  },

  // ─── frontend (+6, 9 total) ─────────────────────────────────────────
  {
    title: "Optimize Core Web Vitals / Page Load Performance",
    slug: "optimize-core-web-vitals-page-load-performance",
    description:
      "Diagnose and fix poor Core Web Vitals scores (LCP, CLS, INP) using real measurement, not guesswork.",
    category: "frontend",
    tags: ["react", "performance"],
    base_instructions:
      "You are a senior frontend engineer improving Core Web Vitals (LCP, CLS, INP) on a page with poor scores. Start by measuring — real field data (e.g. CrUX/RUM) if available, otherwise Lighthouse/PageSpeed Insights — to see which metric is actually failing and why, before making changes. Fix the specific cause (an unoptimized hero image for LCP, layout shift from late-loading content for CLS, a long main-thread task for INP) rather than applying generic 'performance best practices' that may not address the measured problem.",
    fill_in_details_guidance:
      "Stack: [YOUR FRONTEND FRAMEWORK]. The page in question: [URL OR DESCRIPTION]. Current scores, if measured: [PASTE LIGHTHOUSE/PSI/CRUX NUMBERS, OR 'not measured yet, need help running this']. Suspected culprits, if any: [e.g. 'a large above-the-fold image', 'a third-party script', 'client-side data fetching blocking render'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A PRIOR PERFORMANCE OPTIMIZATION YOU'VE DONE ON A SIMILAR PAGE TYPE].",
    reference_links_guidance:
      "[LINK: web.dev'S CORE WEB VITALS GUIDANCE]. [LINK: YOUR FRAMEWORK'S DOCS ON IMAGE OPTIMIZATION / CODE SPLITTING / STREAMING, AS RELEVANT TO THE DIAGNOSED CAUSE].",
    expected_output_notes:
      "A correct response includes: a before measurement for the failing metric(s), the specific diagnosed cause (not a generic checklist), a targeted fix addressing that cause, an after measurement confirming improvement, and a note on how this metric is tracked going forward so it doesn't silently regress.",
  },
  {
    title: "Build a Design System Component Library",
    slug: "build-a-design-system-component-library",
    description:
      "Build a reusable component library with consistent design tokens, variants, and documentation for a design system.",
    category: "frontend",
    tags: ["react", "typescript"],
    base_instructions:
      "You are a senior frontend engineer building a reusable component library to back a design system. Define design tokens (color, spacing, typography) as the single source of truth components consume rather than hardcoding values per-component, implement each component's stated variants and states (including disabled/loading/error where applicable), and make each accessible by default (correct semantics, keyboard support) rather than accessible-as-an-afterthought.",
    fill_in_details_guidance:
      "Stack: [YOUR FRONTEND FRAMEWORK + STYLING APPROACH]. Components needed first: [LIST THEM, e.g. 'Button, Input, Select, Modal']. Design tokens source: [A DESIGN FILE/SPEC TO PULL VALUES FROM, OR 'define reasonable defaults']. Documentation/preview tooling: [e.g. Storybook — or 'recommend one']. Theming requirement: [SINGLE THEME / LIGHT+DARK / MULTI-BRAND].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A COMPONENT LIBRARY WHOSE TOKEN/VARIANT STRUCTURE YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: THE DESIGN SPEC/FIGMA FILE, IF ONE EXISTS]. [LINK: YOUR DOCUMENTATION TOOL'S DOCS, e.g. Storybook].",
    expected_output_notes:
      "A correct response includes: a design-token layer components actually consume (not hardcoded values), the listed components with their stated variants/states implemented, accessible-by-default markup and keyboard support for each, documentation/preview entries for each component, and confirmation the theming requirement (single/light-dark/multi-brand) actually works end-to-end.",
  },
  {
    title: "Implement Optimistic UI Updates",
    slug: "implement-optimistic-ui-updates",
    description:
      "Make a mutating action feel instant with an optimistic UI update, with correct rollback if the server call fails.",
    category: "frontend",
    tags: ["react", "api"],
    base_instructions:
      "You are a senior frontend engineer implementing an optimistic UI update for a mutating action (e.g. liking a post, reordering a list, toggling a setting) so the UI responds instantly instead of waiting on a round trip. Update local state immediately, fire the request in the background, and — this is the part that's usually missed — correctly roll back to the prior state and surface an error if the request actually fails, rather than leaving the UI in a now-incorrect optimistic state.",
    fill_in_details_guidance:
      "Stack: [YOUR FRONTEND FRAMEWORK + DATA-FETCHING LIBRARY, e.g. React Query, SWR, or custom]. The action being made optimistic: [DESCRIBE IT]. Current behavior: [WAITS FOR THE SERVER RESPONSE BEFORE UPDATING UI — CONFIRM THIS IS THE STARTING POINT]. Failure UX preference: [SILENT ROLLBACK + TOAST / INLINE ERROR STATE / OTHER].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN OPTIMISTIC-UPDATE IMPLEMENTATION YOU'VE BUILT BEFORE WITH A ROLLBACK PATTERN YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR DATA-FETCHING LIBRARY'S DOCS ON OPTIMISTIC UPDATES/MUTATIONS].",
    expected_output_notes:
      "A correct response includes: the UI updating instantly on user action (no waiting for the server), the actual request firing in the background, correct rollback to the exact prior state when the request fails (not just any error state), a visible error surfaced to the user matching the stated failure UX, and confirmation concurrent/rapid repeated actions on the same item don't corrupt the rollback state.",
  },
  {
    title: "Build a Command Palette (Cmd+K) Interface",
    slug: "build-a-command-palette-interface",
    description:
      "Add a keyboard-driven command palette for fast navigation and actions, with fuzzy search and full keyboard operability.",
    category: "frontend",
    tags: ["react", "typescript"],
    base_instructions:
      "You are a senior frontend engineer adding a command palette (Cmd/Ctrl+K) for fast keyboard-driven navigation and actions. Implement fuzzy search over the registered commands, full keyboard operability (open, navigate results, select, close — no mouse required at any step), and a way for new commands/pages to register themselves without hand-editing a giant central list. Make sure it doesn't intercept the shortcut while the user is typing in an unrelated text field.",
    fill_in_details_guidance:
      "Stack: [YOUR FRONTEND FRAMEWORK]. Commands/actions to include first: [LIST THEM, e.g. 'navigate to X, create new Y, toggle dark mode']. Search behavior preference: [FUZZY MATCH / EXACT PREFIX / RECOMMEND ONE]. Extensibility need: [DOES A NEW PAGE/FEATURE NEED TO SELF-REGISTER A COMMAND, OR IS A FIXED LIST FINE FOR NOW].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A COMMAND PALETTE WHOSE UX/REGISTRATION PATTERN YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: A COMMAND-PALETTE/COMBOBOX LIBRARY'S DOCS, IF USING ONE, e.g. cmdk]. [LINK: WCAG GUIDANCE ON ACCESSIBLE COMBOBOX/LISTBOX PATTERNS].",
    expected_output_notes:
      "A correct response includes: the palette opening/closing via the stated keyboard shortcut, fuzzy (or stated) search over the listed commands, full keyboard navigation and selection with no mouse dependency, correct focus management (focus returns to the trigger point on close), and confirmation the shortcut doesn't fire while the user is typing in a text input elsewhere on the page.",
  },
  {
    title: "Implement Infinite Scroll / Virtualized List for Large Data",
    slug: "implement-infinite-scroll-virtualized-list",
    description:
      "Render a large or unbounded list performantly with virtualization and correct infinite-scroll pagination.",
    category: "frontend",
    tags: ["react", "performance"],
    base_instructions:
      "You are a senior frontend engineer implementing a large or unbounded list view. Virtualize rendering so only visible (plus a small buffer of) rows are actually in the DOM at once — rendering thousands of real DOM nodes is the usual cause of jank here — and implement infinite-scroll pagination fetching the next page before the user hits the bottom, not after (a visible loading gap). Handle variable-height rows correctly if the data isn't uniform height, and preserve scroll position on navigating back to the list.",
    fill_in_details_guidance:
      "Stack: [YOUR FRONTEND FRAMEWORK]. The data being listed: [DESCRIBE IT AND ROUGH EXPECTED SIZE, e.g. '50k+ rows, variable height cards']. Virtualization library preference: [e.g. TanStack Virtual, react-window — or 'recommend one']. Pagination source: [API SHAPE — CURSOR-BASED OR OFFSET-BASED]. Scroll-position requirement: [MUST BE PRESERVED WHEN NAVIGATING BACK TO THE LIST / NOT NEEDED].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A VIRTUALIZED LIST YOU'VE BUILT BEFORE THAT HANDLED VARIABLE-HEIGHT ROWS OR SCROLL RESTORATION WELL].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN VIRTUALIZATION LIBRARY'S DOCS]. [LINK: YOUR API'S PAGINATION DOCS, IF CURSOR-BASED].",
    expected_output_notes:
      "A correct response includes: virtualized rendering confirmed to keep DOM node count low regardless of total data size, prefetching the next page before the user reaches the bottom (no visible stall), correct handling of variable row heights if applicable, scroll position preserved on back-navigation if that was required, and a tested empty/end-of-list state.",
  },
  {
    title: "Fix Cross-Browser Rendering Inconsistencies",
    slug: "fix-cross-browser-rendering-inconsistencies",
    description:
      "Diagnose and fix a UI that renders differently across browsers, isolating the actual CSS/JS feature gap causing it.",
    category: "frontend",
    tags: ["testing", "react"],
    base_instructions:
      "You are a senior frontend engineer fixing a UI that renders inconsistently across browsers. Isolate the specific CSS property, layout behavior, or JS API causing the divergence (check caniuse.com/MDN browser-support tables rather than guessing) before applying a fix, and prefer a standards-based fix (a supported CSS fallback, a feature-detected code path) over a browser-sniffing hack, which breaks again the next time a browser updates.",
    fill_in_details_guidance:
      "Stack: [YOUR FRONTEND FRAMEWORK]. Browsers affected vs. working correctly: [LIST WHICH BROWSERS/VERSIONS SHOW THE PROBLEM AND WHICH DON'T]. The visual/behavioral difference: [DESCRIBE OR ATTACH A SCREENSHOT COMPARISON]. Browser support requirement: [WHICH BROWSERS/VERSIONS THE APP MUST SUPPORT, e.g. 'last 2 versions of major browsers'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A SIMILAR CROSS-BROWSER ISSUE YOU'VE RESOLVED BEFORE AND HOW].",
    reference_links_guidance:
      "[LINK: caniuse.com OR MDN'S BROWSER-COMPATIBILITY TABLE FOR THE SUSPECTED CSS/JS FEATURE]. [LINK: YOUR CSS AUTOPREFIXER/POLYFILL TOOLING'S DOCS, IF ONE IS ALREADY IN USE].",
    expected_output_notes:
      "A correct response includes: the specific CSS/JS feature identified as the cause (backed by a compatibility-table reference, not a guess), a standards-based fix (fallback or feature detection) rather than user-agent sniffing, confirmation the fix works across every browser in the stated support requirement, and a note on whether this indicates other similar gaps elsewhere in the codebase worth auditing.",
  },

  // ─── backend (+6, 9 total) ───────────────────────────────────────────
  {
    title: "Design a Multi-Tenant Database Schema",
    slug: "design-a-multi-tenant-database-schema",
    description:
      "Design a database schema for a multi-tenant system with enforced, not just assumed, tenant isolation.",
    category: "backend",
    tags: ["postgres", "security"],
    base_instructions:
      "You are a senior backend/database engineer designing a schema for a multi-tenant system. Choose an isolation strategy appropriate to the expected scale and compliance needs (shared tables with a `tenant_id` plus row-level security, schema-per-tenant, or database-per-tenant), and enforce isolation at the database layer rather than relying solely on every application query remembering to filter by tenant. State the tradeoffs of the chosen approach explicitly (cross-tenant query capability, migration complexity, blast radius of a bug).",
    fill_in_details_guidance:
      "Domain: [WHAT THE APP MANAGES PER TENANT]. Expected scale: [TENANT COUNT AND ROUGH DATA VOLUME PER TENANT]. Compliance requirements, if any: [e.g. 'some enterprise customers require data never share physical storage']. Cross-tenant needs, if any: [DOES ANY FEATURE NEED TO QUERY ACROSS TENANTS, e.g. platform-wide admin reporting — or 'none'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A MULTI-TENANT SCHEMA YOU'VE DESIGNED OR SEEN THAT MADE THE RIGHT ISOLATION TRADEOFF FOR A SIMILAR SCALE].",
    reference_links_guidance:
      "[LINK: YOUR DATABASE'S ROW-LEVEL SECURITY DOCS, e.g. Postgres RLS]. [LINK: ANY RELEVANT COMPLIANCE STANDARD'S DATA-ISOLATION REQUIREMENTS].",
    expected_output_notes:
      "A correct response includes: a stated, justified isolation strategy (not a default assumption), the schema with isolation enforced at the database layer, an explicit tradeoff discussion for the chosen approach, a migration path if converting an existing single-tenant schema, and a concrete test proving one tenant cannot read another's data even via a buggy or malicious query.",
  },
  {
    title: "Implement Idempotent API Endpoints",
    slug: "implement-idempotent-api-endpoints",
    description:
      "Make mutating API endpoints safely retryable with idempotency keys, so a client retry never double-processes a request.",
    category: "backend",
    tags: ["api", "postgres"],
    base_instructions:
      "You are a senior backend engineer making mutating endpoints (especially ones with real-world side effects like charging a card or sending an email) safely retryable via idempotency keys. Accept a client-supplied idempotency key, store the result of the first successful processing keyed by it, and return that stored result (not reprocess) on any retry with the same key — including the case where the original request is still in flight when the retry arrives.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Database: [YOUR DATABASE]. Endpoints that need this: [LIST THE MUTATING ENDPOINTS WITH REAL SIDE EFFECTS]. Idempotency key source: [CLIENT-GENERATED HEADER / SERVER-ISSUED — or 'recommend one, e.g. following Stripe's convention']. Key retention window: [HOW LONG A KEY SHOULD BE HONORED, e.g. '24 hours'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN IDEMPOTENCY-KEY IMPLEMENTATION YOU'VE BUILT OR SEEN THAT YOU WANT MIRRORED, e.g. Stripe's API].",
    reference_links_guidance:
      "[LINK: STRIPE'S IDEMPOTENT REQUESTS DOCS, AS A REFERENCE CONVENTION]. [LINK: YOUR DATABASE'S DOCS ON UNIQUE CONSTRAINTS/UPSERTS, FOR THE KEY-STORAGE TABLE].",
    expected_output_notes:
      "A correct response includes: an idempotency-key storage table/mechanism with a unique constraint preventing double-processing, correct handling of the concurrent-retry case (a second request with the same in-flight key waits or is rejected, not double-processed), the stored result returned on retry rather than reprocessing, key expiry per the stated retention window, and test coverage for a genuine concurrent double-submit.",
  },
  {
    title: "Set Up Zero-Downtime Database Migrations",
    slug: "set-up-zero-downtime-database-migrations",
    description:
      "Establish a migration workflow (expand/contract pattern) so schema changes ship without locking tables or breaking live traffic.",
    category: "backend",
    tags: ["postgres", "ci-cd"],
    base_instructions:
      "You are a senior backend engineer establishing a zero-downtime database migration workflow. Use the expand/contract pattern for breaking changes (add the new column/table alongside the old, backfill, switch reads/writes over, only then drop the old one in a later migration) rather than a single migration that renames or drops columns the running application still references. Flag any migration that would take a long-held lock on a large table and propose a non-blocking alternative (e.g. `CREATE INDEX CONCURRENTLY`).",
    fill_in_details_guidance:
      "Database: [YOUR DATABASE]. Migration tool: [e.g. Prisma Migrate, a custom SQL migration runner]. The change being made: [DESCRIBE THE SCHEMA CHANGE, e.g. 'renaming a column', 'splitting a table']. Table size/traffic: [ROUGH ROW COUNT AND WHETHER IT'S HIT BY LIVE TRAFFIC DURING DEPLOYS]. Deployment process: [HOW MIGRATIONS CURRENTLY GET APPLIED RELATIVE TO CODE DEPLOYS].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A ZERO-DOWNTIME MIGRATION YOU'VE DONE BEFORE FOR A SIMILAR CHANGE, e.g. a prior column rename via expand/contract].",
    reference_links_guidance:
      "[LINK: YOUR DATABASE'S DOCS ON NON-BLOCKING SCHEMA CHANGES, e.g. Postgres `CREATE INDEX CONCURRENTLY` and lock behavior of `ALTER TABLE`]. [LINK: YOUR MIGRATION TOOL'S DOCS].",
    expected_output_notes:
      "A correct response includes: the change broken into an expand/contract sequence of migrations (not one breaking migration), confirmation neither the running old code nor new code breaks at any intermediate step, non-blocking techniques used for any large-table operation, an explicit backfill step if data needs copying, and a note on when it's safe to run the final contract (cleanup) migration.",
  },
  {
    title: "Build a Webhook Delivery System With Retries",
    slug: "build-a-webhook-delivery-system-with-retries",
    description:
      "Build outbound webhook delivery to customer endpoints with signing, retry-with-backoff, and delivery visibility.",
    category: "backend",
    tags: ["api", "aws"],
    base_instructions:
      "You are a senior backend engineer building an outbound webhook delivery system to notify customer endpoints of events. Sign every payload (e.g. HMAC) so receivers can verify authenticity, retry failed deliveries with exponential backoff up to a sensible limit, and give customers (or internal ops) visibility into delivery status and a way to inspect/replay a failed delivery. Treat a customer endpoint being slow or down as an expected case, not an exception to crash the sender.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. Events that trigger webhooks: [LIST THEM]. Expected webhook volume: [ROUGH SCALE]. Signing convention preference: [e.g. HMAC-SHA256 IN A HEADER, FOLLOWING A CONVENTION LIKE STRIPE'S — or 'recommend one']. Retry/give-up policy: [MAX RETRIES AND BACKOFF SHAPE, OR 'recommend one'].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A WEBHOOK SYSTEM YOU'VE BUILT OR INTEGRATED WITH WHOSE SIGNING/RETRY CONVENTION YOU WANT MIRRORED, e.g. Stripe or GitHub webhooks].",
    reference_links_guidance:
      "[LINK: STRIPE'S OR GITHUB'S WEBHOOK SIGNING DOCS, AS A REFERENCE CONVENTION]. [LINK: YOUR QUEUE/JOB INFRASTRUCTURE'S DOCS, FOR THE RETRY MECHANISM].",
    expected_output_notes:
      "A correct response includes: a signed payload scheme with verification instructions a receiver could implement, a queued delivery mechanism with exponential backoff up to a stated retry limit, a dead-letter/failed-delivery state after retries are exhausted, a delivery-status view (succeeded/pending/failed per event), and a replay mechanism for a failed delivery.",
  },
  {
    title: "Implement a Redis Caching Layer With Invalidation",
    slug: "implement-a-redis-caching-layer-with-invalidation",
    description:
      "Add a Redis cache in front of an expensive read path, with an explicit, correct invalidation strategy — the actual hard part.",
    category: "backend",
    tags: ["performance", "api"],
    base_instructions:
      "You are a senior backend engineer adding a Redis cache in front of an expensive read path. The caching itself is the easy part; design the invalidation strategy explicitly — what event(s) invalidate which cache keys, and whether a brief staleness window is acceptable (cache-aside with a TTL) or the data must be always-fresh (invalidate-on-write). State the chosen approach and its staleness guarantee rather than leaving it implicit, since a cache with silently-wrong invalidation is worse than no cache at all.",
    fill_in_details_guidance:
      "Stack: [YOUR APP'S TECH STACK]. The expensive read path being cached: [DESCRIBE IT AND WHY IT'S EXPENSIVE]. Redis (or equivalent) availability: [ALREADY PROVISIONED / NEEDS SETTING UP]. Staleness tolerance: [CAN THE DATA BE UP TO N SECONDS/MINUTES STALE, OR MUST WRITES INVALIDATE IMMEDIATELY]. Write paths that should invalidate the cache: [LIST THE OPERATIONS THAT CHANGE THE CACHED DATA].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF A CACHING LAYER YOU'VE BUILT BEFORE WITH AN INVALIDATION STRATEGY YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR CACHE PROVIDER'S DOCS, e.g. Redis]. [LINK: YOUR DATABASE'S DOCS ON CHANGE-DATA-CAPTURE/TRIGGERS, IF INVALIDATION IS EVENT-DRIVEN RATHER THAN CALLED EXPLICITLY FROM WRITE CODE PATHS].",
    expected_output_notes:
      "A correct response includes: the cache-key structure for the read path, a stated invalidation strategy (TTL-based or invalidate-on-write) with its staleness guarantee made explicit, invalidation wired into every listed write path (not just the obvious one), a cache-miss fallback that doesn't stampede the database under concurrent misses, and a note on how to verify cached data actually matches source-of-truth after a write.",
  },
  {
    title: "Design an Event-Driven Architecture With a Message Queue",
    slug: "design-an-event-driven-architecture-with-a-message-queue",
    description:
      "Decouple services with an event/message queue, with clear event contracts, ordering guarantees, and failure handling.",
    category: "backend",
    tags: ["api", "aws"],
    base_instructions:
      "You are a senior backend engineer designing an event-driven integration between services using a message queue or event bus. Define explicit event contracts (schema, versioning approach) rather than letting consumers infer the shape from producer code, state the ordering guarantee the chosen queue actually provides (and whether the design needs it), and handle consumer failure explicitly — what happens to a message that fails processing repeatedly (dead-letter queue, alerting) rather than it silently vanishing or blocking the queue forever.",
    fill_in_details_guidance:
      "Services/components involved: [DESCRIBE THE PRODUCER(S) AND CONSUMER(S)]. Queue/broker preference: [e.g. SQS, Kafka, RabbitMQ, Postgres-backed queue like pgmq — or 'recommend one for this scale']. Events to model first: [LIST THEM]. Ordering requirement: [MUST EVENTS FOR THE SAME ENTITY BE PROCESSED IN ORDER, OR IS ORDER-INDEPENDENT PROCESSING FINE]. Failure tolerance: [WHAT SHOULD HAPPEN TO A MESSAGE THAT REPEATEDLY FAILS TO PROCESS].",
    reference_projects_guidance:
      "[PASTE A LINK OR DESCRIPTION OF AN EVENT-DRIVEN INTEGRATION YOU'VE BUILT BEFORE WITH A CONTRACT/DEAD-LETTER PATTERN YOU WANT MIRRORED].",
    reference_links_guidance:
      "[LINK: YOUR CHOSEN QUEUE/BROKER'S DOCS, INCLUDING ITS ORDERING AND DELIVERY GUARANTEES]. [LINK: A SCHEMA-VERSIONING APPROACH'S DOCS, IF EVENT CONTRACTS NEED TO EVOLVE OVER TIME, e.g. JSON Schema or Avro].",
    expected_output_notes:
      "A correct response includes: explicit event schemas/contracts for every listed event (with a versioning approach for future changes), the producer and at least one consumer wired to the real queue (not an in-memory stub), the actual ordering guarantee of the chosen queue stated and matched against the stated requirement, a dead-letter path and alerting for repeatedly-failing messages, and a note on idempotent consumption (since most queues offer at-least-once delivery, not exactly-once).",
  },
];
